# Generated by Django 4.2.2 on 2023-08-12 23:26

import budget.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('type', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], default='month', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('lower_amount', models.IntegerField(blank=True, null=True)),
                ('upper_amount', models.IntegerField()),
                ('day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Day must be between 1 and 31.'), django.core.validators.MaxValueValidator(31, message='Day must be between 1 and 31.')])),
                ('week', models.IntegerField(blank=True, null=True, validators=[budget.models.validate_week_number])),
                ('week_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Day must be between 0 and 6.'), django.core.validators.MaxValueValidator(6, message='Day must be between 0 and 6.')])),
                ('month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Day must be between 1 and 12.'), django.core.validators.MaxValueValidator(12, message='Day must be between 1 and 12.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week')], default='week', max_length=40)),
                ('offset', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='budget.bill')),
            ],
            options={
                'db_table': 'budget_reminder',
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('type', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], default='month', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('limit_amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
                'db_table': 'budget_category',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent_amount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budgetcategory')),
            ],
            options={
                'db_table': 'budget_alert',
            },
        ),
    ]
