# Generated by Django 4.2.4 on 2023-08-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='type',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='type',
            new_name='period',
        ),
    ]
