# Generated by Django 4.2.4 on 2023-08-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_type_bill_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='category',
            new_name='budget_category',
        ),
    ]
