# Generated by Django 4.2.4 on 2023-08-27 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_rename_category_alert_budget_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='budget_category',
            new_name='category',
        ),
    ]
