# Generated by Django 4.2.4 on 2023-08-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_budgetcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
