# Generated by Django 4.2.4 on 2023-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_bill_created_category_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='monthly', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='period',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], default='monthly', max_length=255),
        ),
    ]
