# Generated by Django 4.2.4 on 2023-09-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_bill_period_alter_category_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.CharField(choices=[('year', 'Yearly'), ('month', 'Monthly')], default='month', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='period',
            field=models.CharField(choices=[('year', 'Yearly'), ('month', 'Monthly')], default='month', max_length=255),
        ),
    ]
