# Generated by Django 4.2.4 on 2023-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_bill_period_alter_category_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
