# Generated by Django 4.2.4 on 2023-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_remove_bill_user_remove_category_user_bill_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='order',
        ),
    ]
