# Generated by Django 4.2.4 on 2023-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_remove_userbill_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.CharField(choices=[('year', 'Yearly'), ('month', 'Monthly'), ('once', 'Once')], default='month', max_length=255),
        ),
    ]
