# Generated by Django 4.2.4 on 2023-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_alter_usercategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(blank=True, default=2023, null=True),
        ),
    ]
