# Generated by Django 4.2.4 on 2023-10-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_bill_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'ordering': ('order',)},
        ),
    ]
