# Generated by Django 4.2.4 on 2023-11-06 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0022_remove_transaction_bill_confirmed_and_more'),
        ('budget', '0018_alter_bill_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.transaction')),
            ],
            options={
                'db_table': 'budget_transaction_category',
                'unique_together': {('transaction', 'category')},
            },
        ),
    ]
