# Generated by Django 4.2.4 on 2023-12-20 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_bill_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Limit must be greater than 0.')]),
        ),
    ]
