# Generated by Django 4.2.4 on 2023-12-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_alter_category_limit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbill',
            name='primary_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercategory',
            name='primary_owner',
            field=models.BooleanField(default=True),
        ),
    ]
