# Generated by Django 4.2.4 on 2024-01-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_userbill_primary_owner_usercategory_primary_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
