# Generated by Django 4.2.4 on 2024-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_bill_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbill',
            name='primary_owner',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='primary_owner',
        ),
        migrations.AddField(
            model_name='bill',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('hidden', 'Hidden')], default='shared', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('hidden', 'Hidden')], default='shared', max_length=10),
        ),
    ]
