# Generated by Django 4.2.4 on 2024-10-09 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_default_reminder_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='percent_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Percent amount must be greater than 0.'), django.core.validators.MaxValueValidator(100, message='Percent amount must be less than 100.')]),
        ),
    ]
