import { createTheme } from '@shopify/restyle';
import { Platform, NativeModules } from 'react-native';
import basePalette from './base-palette';

const { StatusBarManager } = NativeModules;

const grayH = 240;
const grayS = 0;

const blueH = 230;
const blueS = 75;

const greenH = 130;

const palette = {
  ...basePalette,

  red: 'hsl(352, 100%, 68%)',
  mutedRed: 'hsl(352, 98%, 86%)',
  faintRed: 'hsl(352, 55%, 90%)',
  darkRed: 'hsl(352, 59%, 34%)',
  successGreen: 'hsl(144, 62%, 53%)',
  successGreenFaint: 'hsl(144, 62%, 83%)',
  greenText: 'hsl(144, 62%, 43%)',
  coralText: 'hsl(0, 100%, 50%)',
  purpleText: 'hsl(250, 100%, 70%)',

  gray100: `hsl(${grayH}, ${grayS}%, 98%)`,
  gray125: `hsl(${grayH}, ${grayS}%, 96%)`,
  gray150: `hsl(${grayH}, ${grayS}%, 95%)`,
  gray200: `hsl(${grayH}, ${grayS}%, 91%)`,
  gray250: `hsl(${grayH}, ${grayS}%, 89%)`,
  gray275: `hsl(${grayH}, ${grayS}%, 88%)`,
  gray300: `hsl(${grayH}, ${grayS}%, 86%)`,
  gray350: `hsl(${grayH}, ${grayS}%, 84%)`,
  gray400: `hsl(${grayH}, ${grayS}%, 81%)`,
  gray500: `hsl(${grayH}, ${grayS}%, 76%)`,
  gray600: `hsl(${grayH}, ${grayS}%, 71%)`,
  gray700: `hsl(${grayH}, ${grayS}%, 66%)`,
  gray800: `hsl(${grayH}, ${grayS}%, 61%)`,
  gray900: `hsl(${grayH}, ${grayS}%, 56%)`,
  gray1000: `hsl(${grayH}, ${grayS}%, 51%)`,
  gray2000: `hsl(${grayH}, ${grayS}%, 16%)`,

  blue900: `hsl(${blueH}, ${blueS}%, 10%)`,
  blue800: `hsl(${blueH}, ${blueS}%, 20%)`,
  blue700: `hsl(${blueH}, ${blueS}%, 30%)`,
  blue600: `hsl(${blueH}, ${blueS}%, 40%)`,
  blue500: `hsl(${blueH}, ${blueS}%, 50%)`,
  blue450: `hsl(${blueH}, ${blueS}%, 55%)`,
  blue400: `hsl(${blueH}, ${blueS}%, 60%)`,
  blue300: `hsl(${blueH}, ${blueS}%, 70%)`,
  blue250: `hsl(${blueH}, ${blueS}%, 75%)`,
  blue200: `hsl(${blueH}, ${blueS}%, 85%)`,
  blue100: `hsl(${blueH}, ${blueS}%, 90%)`,
  blue50: `hsl(${blueH}, ${blueS}%, 92%)`,

  blueSat: `hsl(${blueH}, ${blueS + 10}%, 50%)`,

  black: 'hsl(0, 0%, 0%)',
  offBlack: `hsl(${grayH}, ${grayS}%, 0%)`,
  offBlack2: `hsl(${grayH}, ${grayS}%, 30%)`,
  offBlack3: `hsl(${grayH}, ${grayS}%, 60%)`,
  offBlack4: `hsl(${grayH}, ${grayS}%, 70%)`,
  offBlack5: `hsl(${grayH}, ${grayS}%, 80%)`,
  offBlack6: `hsl(${grayH}, ${grayS}%, 900%)`,
};

export const lightTheme = createTheme({
  colors: {
    transparent: 'transparent',
    mode: 'light',
    blueHue: `${blueH}`,

    // Backgrounds
    mainBackground: palette.gray125,
    accountsMainBackground: palette.gray100,
    bottomNavCover: palette.gray125,
    androidNavBar: palette.gray200,
    bottomNavBackground: palette.gray125,
    lightGrayCard: palette.gray250,
    inputBackground: palette.gray250,
    nestedContainer: palette.white,
    modalNestedContainer: palette.gray200,
    avatar: palette.gray500,
    modalOverlay: palette.gray900.replace(`${grayS}`, '0'),
    modalBox: palette.gray150,
    modalBox100: palette.gray100,
    nestedModalContainer: palette.gray200,
    newTransaction: palette.gray100,
    contextMenu: palette.gray100,
    toast: palette.white,
    widgetPickerBackground: palette.gray150,
    widget: palette.white,
    tooltip: palette.black,
    creditCardDefaultGradientStart: `hsl(${blueH}, 1%, 70%)`,
    creditCardDefaultGradientEnd: `hsl(${blueH}, 1%, 60%)`,

    // Borders
    creditCardDefaultBorder: 'transparent',
    inputBorder: palette.gray250,
    inputBorderErrorSecondary: palette.mutedRed,
    inputBorderErrorMain: palette.red,
    focusedInputBorderSecondary: palette.blue50,
    focusedInputBorderMain: palette.blue300,
    tabNavPillBorder: palette.blue100,
    bottomNavBorder: Platform.OS === 'ios' ? palette.gray200 : palette.white,
    nestedContainerBorder: `hsl(${grayH}, ${grayS}%, 94%)`,
    tabNavBorder: palette.gray250,
    newTransactionBorder: palette.gray150,
    contextMenuBorder: palette.gray250,
    modalBorder: palette.gray200,
    toastBorder: palette.gray100,
    contextMenuDivider: palette.gray200,
    containerDragBar: palette.gray500,

    // Shadows
    navShadow: palette.gray400,
    modalShadow: palette.gray800.replace(`${grayS}`, '0'),
    tabsShadow: palette.gray300,
    activeIcon: palette.blueSat,
    activeSwitchShadow: 'hsl(144, 70%, 50%)',
    disabledSwitchShadow: palette.gray500,
    logoShadow: palette.gray500,
    newTransactionShadow:
      Platform.OS === 'ios' ? palette.gray200 : palette.gray300,
    menuShadowColor: palette.gray400,
    creditCardShadow: palette.gray300,

    // Text
    mainText: palette.offBlack,
    secondaryText: palette.offBlack2,
    tertiaryText: palette.offBlack3,
    quaternaryText: palette.offBlack4,
    quinaryText: palette.offBlack5,
    whiteText: palette.white,
    blackText: palette.black,
    highContrastText: palette.black,
    invertedText: palette.gray100,
    activeText: palette.blueSat,
    blueText: palette.blueSat,
    blueTextSecondary: palette.blue500.replace(`${blueS}`, `${blueS - 10}`),
    greenText: palette.greenText,
    placeholderText: palette.offBlack3,
    buttonLabel: palette.offBlack,
    faintBlueText: palette.blue300,
    footerText: palette.gray600,
    redText: palette.red,
    purpleText: palette.purpleText,

    // Buttons
    lightBlueButton: palette.blue100,
    lightBlueButtonBorder: palette.blue200,
    mediumBlueButton: palette.blue200,
    mediumBlueButtonBorder: palette.blue250,
    blueButton: palette.blue400,
    blueButtonBorder: palette.blue450,
    blueButtonBorder2: palette.blue100,
    lightGrayButton: palette.gray150,
    lightGrayButtonBorder: palette.gray100,
    grayButton: palette.gray250,
    grayButtonBorder: palette.gray300,
    mediumGrayButton: palette.gray500,
    mediumGrayButtonBorder: palette.gray600,
    tabNavPill: palette.blue100,
    borderedGrayButton: palette.gray200,
    dragBar: palette.gray300,
    tabsTrack: palette.gray200,
    tabsBackground: palette.gray100,
    radioCardSelected: palette.gray200,
    radioCardUnselected: palette.gray150,
    redButton: palette.faintRed,

    // Category and Bill Colors
    monthBackground: `hsl(${blueH}, 100%, 93%)`,
    monthBorder: `hsl(${blueH}, 100%, 91%)`,
    monthBorder2: `hsl(${blueH}, 100%, 80%)`,
    monthColor: `hsl(${blueH}, 80%, 58%)`,
    yearBackground: `hsl(${greenH}, 70%, 88%)`,
    yearBorder: `hsl(${greenH}, 70%, 84%)`,
    yearBorder2: `hsl(${greenH}, 70%, 73%)`,
    yearColor: `hsl(${greenH}, 80%, 38%)`,

    // Switch
    enabledSwitchPill: palette.gray100,
    enabledSwitchCrib: 'hsl(144, 70%, 65%)',
    disabledSwitchPill: palette.gray150,
    disabledSwitchCrib: palette.gray300,

    // Seperators
    seperator: palette.gray200,
    modalSeperator: palette.gray150,
    menuSeperator: palette.gray200,
    mainScreenSeperator: palette.gray200,
    nestedContainerSeperator: palette.gray125,
    authScreenSeperator: palette.gray250,

    // Misc
    alert: palette.red,
    pulseWaiting: palette.gray300,
    pulseGreen: palette.successGreenFaint,
    scrollbar: palette.gray250,
    pulseBox: palette.gray200,

    blueChartGradientStart: palette.blue50,
    blueChartGradientEnd: palette.gray200
      .replace('hsl', 'hsla')
      .replace(')', ', 0)'),
    modalShadowMaskEnd: `hsla(${grayH}, ${grayS}%, 95%, 0)`,
    blueChartColor: palette.blue300,
    blueChartColorSecondary: palette.blue200,
    emptyChartGradientStart: palette.gray300,
    emptyChartColor: palette.gray400,

    // Icons
    successIcon: palette.successGreen,
    grayIcon: palette.gray400,
  },
  spacing: {
    none: 0,
    xxxs: 1,
    xxs: 2,
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 24,
    xxl: 36,
    xxxl: 48,
    xxxxl: 54,
    navHeight: 104,
    statusBar: StatusBarManager.HEIGHT + 4,
    pagePadding: 16,
    nestedContainerVPadding: 12,
    nestedContainerHPadding: 16,
  },
  textVariants: {
    regular: {
      fontFamily: 'SourceSans3Regular',
      color: 'mainText',
    },
    bold: {
      fontFamily: 'SourceSans3SemiBold',
      color: 'highContrastText',
    },
    geistRegular: {
      fontFamily: 'GeistRegular',
      color: 'mainText',
    },
    geistMedium: {
      fontFamily: 'GeistMedium',
      color: 'mainText',
    },
    geistSemiBold: {
      fontFamily: 'GeistSemiBold',
      color: 'mainText',
    },
    geistBold: {
      fontFamily: 'GeistBold',
      color: 'mainText',
    },
    header: {
      fontSize: 24,
      lineHeight: 28,
      marginVertical: 'm',
      marginLeft: 'xs',
      marginBottom: 'xs',
      fontFamily: 'SourceSans3SemiBold',
    },
    header2: {
      fontSize: 20,
      marginLeft: 'xs',
      lineHeight: 24,
      fontFamily: 'SourceSans3SemiBold',
      marginTop: 'm',
      marginBottom: 's',
    },
    boxHeader: {
      fontSize: 15,
      lineHeight: 20,
      fontFamily: 'SourceSans3Regular',
      alignItems: 'center',
      marginTop: 'l',
      gap: 's',
      marginLeft: 'xs',
      color: 'tertiaryText',
    },
    subheader: {
      fontSize: 24,
      lineHeight: 40,
      marginLeft: 'xs',
      marginTop: 's',
      marginBottom: 's',
      fontFamily: 'SourceSans3Medium',
      color: 'secondaryText',
    },
    subheader2: {
      fontSize: 16,
      marginLeft: 'xs',
      lineHeight: 22,
      fontFamily: 'SourceSans3Medium',
      color: 'tertiaryText',
    },
    label: {
      marginLeft: 'xs',
      fontFamily: 'SourceSans3Medium',
      color: 'secondaryText',
    },
    defaults: {
      fontSize: Platform.OS === 'ios' ? 16 : 17,
      lineHeight: 24,
      fontFamily: 'SourceSans3Regular',
      color: 'mainText',
    },
    footer: {
      fontSize: 14,
      lineHeight: 16,
      marginVertical: 's',
      fontFamily: 'SourceSans3Regular',
      color: 'footerText',
    },
  },
  buttonVariants: {
    main: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'blueButton',
      color: 'whiteText',
      // borderWidth: 1.5,
      // borderColor: 'blueButtonBorder',
    },
    blueMain2: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'blueButton2',
      // borderWidth: 1.5,
      // borderColor: 'blueButtonBorder2',
      color: 'blueText',
    },
    grayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'grayButton',
      color: 'mainText',
      // borderWidth: 1.5,
      // borderColor: 'grayButtonBorder',
    },
    dashedMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: 'grayButtonBorder',
      color: 'quaternaryText',
      borderStyle: 'dashed',
    },
    mediumGrayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'mediumGrayButton',
      // borderWidth: 1.5,
      // color: 'mainText',
      borderColor: 'mediumGrayButtonBorder',
    },
    borderedGrayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 'm',
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'borderedGrayButton',
      color: 'secondaryText',
    },
    blueBorderedMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      borderRadius: 'm',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 1.5,
      // borderColor: 'blueseperator',
      color: 'blueText',
    },
    socialSignIn: {
      padding: 's',
      borderRadius: 'l',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'authScreenSeperator',
      flexDirection: 'row',
    },
    grayLinkButton: {
      color: 'tertiaryText',
      paddingVertical: 'xxs',
    },
    grayPill: {
      paddingVertical: 'xxxs',
      paddingHorizontal: 'm',
      borderRadius: 'circle',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'grayButton',
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    borderedPill: {
      color: 'secondaryText',
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 'circle',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.25,
      borderColor: 'borderedGrayButton',
    },
    bluePill: {
      paddingVertical: 'xxxs',
      paddingHorizontal: 'm',
      borderRadius: 'circle',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'blueButton',
      color: 'whiteText',
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    blueBorderedPill: {
      color: 'blueText',
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 'circle',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.25,
      borderColor: 'focusedInputBorderMain',
    },
    transparentPill: {
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 'circle',
      alignItems: 'center',
      // borderWidth: 1.5,
      // borderColor: 'transparent',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    circleButton: {
      padding: 'xs',
      borderRadius: 'circle',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'grayButton',
    },
    defaults: {
      padding: 's',
      alignItems: 'center',
      flexDirection: 'row',
      color: 'mainText',
      fontSize: 16,
      letterSpacing: 2,
    },
    square: {
      padding: 's',
      borderRadius: 's',
    },
    rectangle: {
      paddingHorizontal: 'm',
      paddingVertical: 's',
      borderRadius: 'm',
    },
    bold: {
      fontFamily: 'SourceSans3Medium',
    },
  },
  seperatorVariants: {
    bare: {
      height: 1.25,
      backgroundColor: 'seperator',
    },
    s: {
      height: 1.25,
      marginVertical: 's',
      backgroundColor: 'seperator',
    },
    m: {
      height: 1.25,
      marginVertical: 'l',
      backgroundColor: 'seperator',
    },
    l: {
      height: 1.25,
      marginVertical: 'xl',
      backgroundColor: 'seperator',
    },
    xl: {
      height: 1.25,
      marginVertical: 'xxxl',
      backgroundColor: 'seperator',
    },
    defaults: {},
  },
  borderRadii: {
    none: 0,
    xxs: 4,
    xs: 6,
    s: 8,
    m: 12,
    l: 16,
    xl: 20,
    circle: 9999,
  },
  boxVariants: {
    header: {
      paddingHorizontal: 'l',
    },
    fullCentered: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: 'l',
    },
    even: {
      flex: 1,
      justifyContent: 'space-evenly',
    },
    screen: {
      flex: 1,
      paddingHorizontal: 'l',
      paddingTop: 'statusBar',
    },
    nestedScreen: {
      flex: 1,
      paddingHorizontal: 'l',
      paddingTop: 'statusBar',
      marginTop: 'xxxl',
    },
    screenContent: {
      flex: 1,
      paddingHorizontal: 'xl',
      marginBottom: 'navHeight',
      paddingTop: 'm',
    },
    nestedContainer: {
      borderRadius: 'l',
      paddingHorizontal: 'nestedContainerHPadding',
      paddingVertical: 'nestedContainerVPadding',
      marginVertical: 's',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      backgroundColor: 'nestedContainer',
      borderColor: 'transparent',
      borderWidth: 1.5,
    },
    lightGrayCard: {
      paddingHorizontal: 'l',
      paddingVertical: 'm',
      borderRadius: 'm',
      backgroundColor: 'lightGrayCard',
    },
    bottomNav: {
      paddingHorizontal: 'l',
    },
    footer: {
      position: 'absolute',
      flexDirection: 'row',
      justifyContent: 'center',
      paddingBottom: 'xl',
      right: 24,
      left: 24,
      bottom: 0,
      zIndex: 100,
    },
    dragBar: {
      backgroundColor: 'dragBar',
      width: 32,
      height: 5,
      borderRadius: 'circle',
      position: 'absolute',
      top: 6,
    },
    largerDragBar: {
      backgroundColor: 'dragBar',
      width: 38,
      height: 7,
      borderRadius: 'circle',
      position: 'absolute',
      top: 6,
    },
    dragBarContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: 24,
    },
    divider: {
      width: 2,
      height: 20,
      borderRadius: 'circle',
      marginHorizontal: 's',
    },
    carouselDot: {
      width: 5,
      height: 5,
      borderRadius: 'circle',
      backgroundColor: 'mainText',
    },
    defaults: {},
  },
});

export type Theme = typeof lightTheme;
