import { createTheme } from '@shopify/restyle';
import { Platform, NativeModules } from 'react-native';
import basePalette from './base-palette';

const { StatusBarManager } = NativeModules;

const grayH = 240;
const grayS = 7;

const blueH = 230;
const blueS = 50;

const greenH = 130;

const palette = {
  ...basePalette,

  red: 'hsl(0, 55%, 68%)',
  mutedRed: 'hsl(352, 98%, 86%)',
  darkRed: 'hsl(0, 59%, 34%)',
  successGreen: 'hsl(144, 62%, 53%)',
  successGreenFaint: 'hsl(144, 62%, 83%)',
  greenText: 'hsl(144, 62%, 53%)',

  gray100: `hsl(${grayH}, ${grayS}%, 98%)`,
  gray150: `hsl(${grayH}, ${grayS}%, 95%)`,
  gray200: `hsl(${grayH}, ${grayS}%, 91%)`,
  gray250: `hsl(${grayH}, ${grayS}%, 89%)`,
  gray275: `hsl(${grayH}, ${grayS}%, 88%)`,
  gray300: `hsl(${grayH}, ${grayS}%, 86%)`,
  gray350: `hsl(${grayH}, ${grayS}%, 84%)`,
  gray400: `hsl(${grayH}, ${grayS}%, 81%)`,
  gray500: `hsl(${grayH}, ${grayS}%, 76%)`,
  gray600: `hsl(${grayH}, ${grayS}%, 71%)`,
  gray700: `hsl(${grayH}, ${grayS}%, 66%)`,
  gray800: `hsl(${grayH}, ${grayS}%, 61%)`,
  gray900: `hsl(${grayH}, ${grayS}%, 56%)`,
  gray1000: `hsl(${grayH}, ${grayS}%, 51%)`,
  gray2000: `hsl(${grayH}, ${grayS}%, 16%)`,

  blue900: `hsl(${blueH}, ${blueS}%, 10%)`,
  blue800: `hsl(${blueH}, ${blueS}%, 20%)`,
  blue700: `hsl(${blueH}, ${blueS}%, 30%)`,
  blue600: `hsl(${blueH}, ${blueS}%, 40%)`,
  blue500: `hsl(${blueH}, ${blueS}%, 50%)`,
  blue450: `hsl(${blueH}, ${blueS}%, 55%)`,
  blue400: `hsl(${blueH}, ${blueS}%, 60%)`,
  blue300: `hsl(${blueH}, ${blueS}%, 70%)`,
  blue200: `hsl(${blueH}, ${blueS}%, 80%)`,
  blue100: `hsl(${blueH}, ${blueS}%, 90%)`,
  blue50: `hsl(${blueH}, ${blueS}%, 92%)`,

  blueSat: `hsl(${blueH}, ${blueS + 10}%, 50%)`,

  black: 'hsl(0, 0%, 0%)',
  offBlack: `hsl(${grayH}, ${grayS}%, 25%)`,
  offBlack2: `hsl(${grayH}, ${grayS}%, 42%)`,
  offBlack3: `hsl(${grayH}, ${grayS}%, 60%)`,
  offBlack4: `hsl(${grayH}, ${grayS}%, 70%)`,
  offBlack5: `hsl(${grayH}, ${grayS}%, 80%)`,
  offBlack6: `hsl(${grayH}, ${grayS}%, 900%)`,
}

export const lightTheme = createTheme({
  colors: {
    transparent: 'transparent',
    mode: 'light',

    // Backgrounds
    mainBackground: palette.gray150,
    accountsMainBackground: palette.gray100,
    bottomNavCover: palette.gray300,
    androidNavBar: palette.gray200,
    bottomNavBackground: Platform.OS === 'ios' ? palette.gray500 : palette.gray400,
    inputBackground: palette.gray250,
    nestedContainer: palette.white,
    avatar: palette.gray500,
    modalOverlay: palette.gray900.replace(`${grayS}`, '0'),
    modalBox: palette.gray150,
    modalBox100: palette.gray100,
    nestedModalContainer: palette.gray200,
    newTransaction: palette.gray200,
    contextMenu: palette.gray100,
    toast: palette.white,

    // Borders
    inputBorder: palette.gray300,
    inputBorderErrorSecondary: palette.mutedRed,
    inputBorderErrorMain: palette.red,
    focusedInputBorderSecondary: palette.blue100,
    focusedInputBorderMain: palette.blue300,
    tabNavPillBorder: palette.blue100,
    bottomNavBorder: Platform.OS === 'ios' ? palette.gray600 : palette.gray500,
    nestedContainerBorder: `hsl(${grayH}, ${grayS}%, 93%)`,
    tabNavBorder: palette.gray250,
    newTransactionBorder: palette.gray250,
    contextMenuBorder: palette.gray200,
    modalBorder: palette.gray200,
    toastBorder: palette.gray100,
    contextMenuDivider: palette.gray200,

    // Shadows
    navShadow: palette.gray200,
    modalShadow: palette.gray800.replace(`${grayS}`, '0'),
    tabsShadow: palette.gray300,
    activeIcon: palette.blueSat,
    activeSwitchShadow: 'hsl(144, 70%, 50%)',
    disabledSwitchShadow: palette.gray500,
    logoShadow: palette.gray500,
    newTransactionShadow: palette.gray300,
    menuShadowColor: palette.gray400,

    // Text
    mainText: palette.offBlack,
    secondaryText: palette.offBlack2,
    tertiaryText: palette.offBlack3,
    quaternaryText: palette.offBlack4,
    quinaryText: palette.offBlack5,
    whiteText: palette.white,
    highContrastText: palette.black,
    invertedText: palette.gray100,
    activeText: palette.blueSat,
    blueText: palette.blueSat,
    blueTextSecondary: palette.blue500.replace(`${blueS}`, `${blueS - 10}`),
    greenText: palette.greenText,
    placeholderText: palette.offBlack3,
    buttonLabel: palette.offBlack,

    // Buttons
    lightBlueButton: palette.blue50,
    lightBlueButtonBorder: palette.blue100,
    blueButton: palette.blue500,
    blueButtonBorder: palette.blue450,
    blueButtonBorder2: palette.blue100,
    lightGrayButton: palette.gray150,
    lightGrayButtonBorder: palette.gray200,
    grayButton: palette.gray250,
    grayButtonBorder: palette.gray275,
    mediumGrayButton: palette.gray250,
    mediumGrayButtonBorder: palette.gray300,
    tabNavPill: palette.blue100,
    tabGrayPill: palette.gray1000,
    tabGrayPillBorder: 'transparent',
    borderedGrayButton: palette.gray200,
    dragBar: palette.gray300,

    // Category and Bill Colors
    monthBackground: `hsl(${blueH}, 67%, 93%)`,
    monthBorder: `hsl(${blueH}, 50%, 86%)`,
    monthColor: `hsl(${blueH}, 80%, 58%)`,
    yearBackground: `hsl(${greenH}, 55%, 91%)`,
    yearBorder: `hsl(${greenH}, 40%, 82%)`,
    yearColor: `hsl(${greenH}, 50%, 38%)`,

    // Switch
    enabledSwitchPill: palette.gray100,
    enabledSwitchCrib: 'hsl(144, 70%, 65%)',
    disabledSwitchPill: palette.gray150,
    disabledSwitchCrib: palette.gray300,

    // Seperators
    lightseperator: palette.gray150,
    darkerseperator: palette.gray250,
    menuSeperator: palette.gray200,
    blueseperator: palette.blue100,

    // Misc
    alert: palette.red,
    pulseWaiting: palette.gray300,
    pulseGreen: palette.successGreenFaint,
    scrollbar: palette.gray250,
    transactionShimmer: palette.gray200,

    // Icons
    successIcon: palette.successGreen,
    grayIcon: palette.gray400,
  },
  spacing: {
    none: 0,
    xxs: 2,
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 24,
    xxl: 36,
    xxxl: 48,
    xxxxl: 54,
    navHeight: 104,
    statusBar: StatusBarManager.HEIGHT,
  },
  textVariants: {
    bold: {
      fontFamily: 'SourceSans3SemiBold',
      color: 'highContrastText',
    },
    header: {
      fontSize: 26,
      lineHeight: 30,
      marginVertical: 'm',
      marginLeft: 'xs',
      marginBottom: 'xs',
      fontFamily: 'SourceSans3SemiBold',
    },
    header2: {
      fontSize: 20,
      marginLeft: 'xs',
      lineHeight: 24,
      fontFamily: 'SourceSans3Medium',
      marginTop: 'm',
      marginBottom: 's',
    },
    boxHeader: {
      fontSize: 15,
      lineHeight: 20,
      fontFamily: 'SourceSans3Medium',
      marginTop: 'l',
      marginLeft: 'xs',
      color: 'tertiaryText',
    },
    subheader: {
      fontSize: 24,
      lineHeight: 40,
      marginLeft: 'xs',
      marginTop: 's',
      marginBottom: 's',
      fontFamily: 'SourceSans3Medium',
      color: 'secondaryText',
    },
    subheader2: {
      fontSize: 16,
      marginLeft: 'xs',
      lineHeight: 22,
      fontFamily: 'SourceSans3Medium',
      color: 'tertiaryText',
    },
    label: {
      marginLeft: 'xs',
      fontFamily: 'SourceSans3Medium',
      color: 'secondaryText',
    },
    defaults: {
      fontSize: 16,
      lineHeight: 24,
      fontFamily: 'SourceSans3Regular',
      color: 'mainText',
    },
    footer: {
      fontSize: 14,
      lineHeight: 16,
      marginVertical: 's',
      fontFamily: 'SourceSans3Regular',
      color: 'quaternaryText',
    }
  },
  buttonVariants: {
    main: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'blueButton',
      color: 'whiteText',
      // borderWidth: 1.5,
      // borderColor: 'blueButtonBorder',
    },
    blueMain2: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'blueButton2',
      // borderWidth: 1.5,
      // borderColor: 'blueButtonBorder2',
      color: 'blueText',
    },
    grayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'grayButton',
      color: 'mainText',
      // borderWidth: 1.5,
      // borderColor: 'grayButtonBorder',
    },
    dashedMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: 'grayButtonBorder',
      color: 'quaternaryText',
      borderStyle: 'dashed',
    },
    mediumGrayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'mediumGrayButton',
      // borderWidth: 1.5,
      // color: 'mainText',
      borderColor: 'mediumGrayButtonBorder',
    },
    borderedGrayMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      marginVertical: 's',
      borderRadius: 12,
      gap: 's',
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'borderedGrayButton',
      color: 'secondaryText',
    },
    blueBorderedMain: {
      paddingHorizontal: 'm',
      paddingVertical: Platform.OS === 'ios' ? 'm' : 'l',
      borderRadius: 12,
      marginHorizontal: 'xxs',
      alignItems: 'center',
      justifyContent: 'center',
      // borderWidth: 1.5,
      // borderColor: 'blueseperator',
      color: 'blueText',
    },
    socialSignIn: {
      padding: 's',
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: 'darkerseperator',
      flexDirection: 'row',
    },
    grayLinkButton: {
      color: 'tertiaryText',
      paddingVertical: 'xxs',
    },
    grayPill: {
      color: 'tertiaryText',
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'grayButton',
      borderWidth: 1.5,
      borderColor: 'grayButtonBorder',
    },
    borderedPill: {
      color: 'secondaryText',
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.25,
      borderColor: 'borderedGrayButton',
    },
    blueBorderedPill: {
      color: 'blueText',
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderWidth: 1.25,
      borderColor: 'focusedInputBorderMain',
    },
    transparentPill: {
      paddingVertical: 'xxs',
      paddingHorizontal: 'm',
      borderRadius: 40,
      alignItems: 'center',
      // borderWidth: 1.5,
      // borderColor: 'transparent',
      justifyContent: 'center',
      backgroundColor: 'transparent',
    },
    circleButton: {
      padding: 'xs',
      borderRadius: 40,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'mediumGrayButton',
    },
    defaults: {
      padding: 's',
      alignItems: 'center',
      flexDirection: 'row',
      color: 'mainText',
      fontSize: 16,
      letterSpacing: 2,
    },
    bold: {
      fontFamily: 'SourceSans3Medium',
    }
  },
  seperatorVariants: {
    bare: {
      height: 1.25,
      backgroundColor: 'lightseperator',
    },
    s: {
      height: 1.25,
      marginVertical: 's',
      backgroundColor: 'lightseperator',
    },
    m: {
      height: 1.25,
      marginVertical: 'l',
      backgroundColor: 'lightseperator',
    },
    l: {
      height: 1.25,
      marginVertical: 'xl',
      backgroundColor: 'lightseperator',
    },
    xl: {
      height: 1.25,
      marginVertical: 'xxxl',
      backgroundColor: 'lightseperator',
    },
    defaults: {}
  },
  boxVariants: {
    header: {
      paddingHorizontal: 'l'
    },
    fullCentered: {
      flex: 1,
      justifyContent: 'center',
      paddingHorizontal: 'l',
    },
    even: {
      flex: 1,
      justifyContent: 'space-evenly'
    },
    screen: {
      flex: 1,
      paddingHorizontal: 'l',
      paddingTop: 'statusBar',
    },
    nestedScreen: {
      flex: 1,
      paddingHorizontal: 'l',
      paddingTop: 'statusBar',
      marginTop: 'xxxl'
    },
    screenContent: {
      flex: 1,
      paddingHorizontal: 'xl',
      marginBottom: 'navHeight',
      paddingTop: 'm',
    },
    nestedContainer: {
      borderRadius: 12,
      paddingVertical: 'm',
      paddingHorizontal: 'l',
      marginVertical: 's',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      backgroundColor: 'nestedContainer',
      borderColor: 'nestedContainerBorder',
      borderWidth: 1.5,
    },
    bottomNav: {
      paddingHorizontal: 'l',
    },
    footer: {
      position: 'absolute',
      flexDirection: 'row',
      justifyContent: 'center',
      paddingBottom: 'xl',
      right: 24,
      left: 24,
      bottom: 0,
      zIndex: 100
    },
    dragBar: {
      backgroundColor: 'dragBar',
      width: 54,
      height: 6,
      borderRadius: 5,
      position: 'absolute',
      top: 6
    },
    dragBarContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: 24
    },
    divider: {
      width: 2,
      height: 20,
      borderRadius: 4,
      marginHorizontal: 'l',
    },
    defaults: {}
  },
});

export type Theme = typeof lightTheme;
