# Generated by Django 4.2.1 on 2023-06-06 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_flag', models.CharField(choices=[('service_abuse', 'Service abuse')], default=None, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('created', models.IntegerField(editable=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('service_expiration', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
                ('unit_amount', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.IntegerField(editable=False)),
                ('livemode', models.BooleanField(default=False)),
                ('lookup_key', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('contract_length', models.IntegerField(default=0)),
                ('trial_period_days', models.IntegerField(default=0)),
                ('renews', models.CharField(default='monthly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
                ('created', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('trialing', 'trialing'), ('active', 'active'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('past_due', 'past_due'), ('unpaid', 'unpaid'), ('canceled', 'canceled')], max_length=20)),
                ('client_secret', models.CharField(max_length=100, null=True)),
                ('current_period_end', models.IntegerField(null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('default_payment_method', models.CharField(max_length=100, null=True)),
                ('trial_start', models.IntegerField(editable=False, null=True)),
                ('trial_end', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.customer')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.price')),
            ],
        ),
    ]
