# Generated by Django 4.2.2 on 2023-08-12 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account_flag', models.CharField(choices=[('service_abuse', 'Service abuse')], default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Field must contain only letters and numbers.', regex='^[a-zA-Z0-9-]{15,}+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('subscription_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='incomplete', max_length=20, null=True)),
                ('provisioned_until', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
