# Generated by Django 4.2.1 on 2023-06-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('unpaid', 'Unpaid')], default='incomplete', max_length=20, null=True),
        ),
    ]
