# Generated by Django 4.2.2 on 2023-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='provisioned_until',
            new_name='period_end',
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused')], default='incomplete', max_length=20, null=True),
        ),
    ]
