# Generated by Django 4.2.4 on 2023-08-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
