# Generated by Django 4.2.2 on 2023-07-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('incomplete', 'Incomplete'), ('past_due', 'Past Due'), ('paused', 'Paused')], default='incomplete', max_length=20, null=True),
        ),
    ]
