# Generated by Django 4.2.4 on 2023-08-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_onboarded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='onboarded',
            new_name='is_onboarded',
        ),
    ]
