# Generated by Django 4.2.2 on 2023-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], default='incomplete', max_length=20, null=True),
        ),
    ]
