# Generated by Django 4.2.2 on 2023-08-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plaiditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaiditem',
            old_name='accessToken',
            new_name='access_token',
        ),
    ]
