# Generated by Django 4.2.4 on 2023-09-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_cancel_at_period_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cancel_at_period_end',
        ),
    ]
