# Generated by Django 4.2.4 on 2023-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_customer_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cancelation_reason',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='feedback',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
