# Generated by Django 4.2.2 on 2023-08-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_accesstoken_plaiditem_access_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plaiditem',
            table='plaid_items',
        ),
    ]
