# Generated by Django 4.2.2 on 2023-08-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_plaiditem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plaiditem',
            table='core_plaid_item',
        ),
    ]
