# Generated by Django 4.2.4 on 2023-09-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_hash_device_token_device_mfa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mfa',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa',
            field=models.BooleanField(default=False),
        ),
    ]
