# Generated by Django 4.2.4 on 2023-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_user_authenticator_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authenticator_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='authenticator_enabled_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
