# Generated by Django 4.2.4 on 2023-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_authenticator_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='user_agent',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
