# Generated by Django 4.2.4 on 2023-09-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_device_aal'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
