# Generated by Django 4.2.4 on 2023-09-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_user_authenticator_enabled_user_mfa_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('authenticator', 'Authenticator'), ('email', 'Email'), ('phone', 'Phone')], default=None, null=True),
        ),
    ]
