# Generated by Django 4.2.4 on 2023-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_device_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='device',
            name='browser_family',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='browser_version',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_family',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_touch_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='os_family',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_version',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
