# Generated by Django 4.2.4 on 2023-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_device_agent_type_remove_device_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
