# Generated by Django 4.2.4 on 2023-09-26 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_user_password_last_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='authenticator_enabled_on',
            new_name='mfa_enabled_on',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_device',
            field=models.CharField(choices=[('totp', 'Authenticator'), ('email', 'Email'), ('phone', 'Phone')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('hotp', 'HOTP')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
