# Generated by Django 4.2.4 on 2023-09-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_device',
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('hotp', 'HOTP')], default='hotp', max_length=4, null=True),
        ),
    ]
