# Generated by Django 4.2.4 on 2023-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_device_aal_alter_user_mfa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp_verification',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='aal',
            field=models.CharField(choices=[('aal1', 'AAL1'), ('aal15', 'AAL15'), ('aal2', 'AAL2')], default='aal1', max_length=7),
        ),
    ]
