# Generated by Django 4.2.4 on 2023-10-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_canceled_on_user_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
