# Generated by Django 4.2.4 on 2023-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_user_password_last_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_co_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='yearly_categories_anchor',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
