# Generated by Django 4.2.4 on 2024-02-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_user_mfa_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_otp_verification',
        ),
    ]
