version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
  api:
    build:
      args:
        - DEV=true
      context: ./back
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runsslserver --cert /run/secrets/ledget_ssl_cert --key /run/secrets/ledget_ssl_key"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
    secrets:
      - stripe_webhook_secret
      - stripe_api_key
      - django_secret_key
      - postgres_user
      - postgres_password
      - ledget_ssl_cert
      - ledget_ssl_key
    volumes:
      - ./logs:/ledgetapi/logs
    depends_on:
      - db
  stripe-listener:
    image: stripe/stripe-cli
    env_file:
      - ./secrets/.env.stripe.dev
    command: listen --forward-to https://ledget.app:8000/api/v1/stripe-hook --skip-verify
    secrets:
      - stripe_api_key
  home:
    build:
      args:
        - DEV=true
        - NAME=home
      context: ./app
      dockerfile: Dockerfile.dev
    command: npm start
    depends_on:
      - api
    secrets:
      - localhost_ssl_cert
      - localhost_ssl_key
      - ca_cert
  portal:
    build:
      args:
        - DEV=true
        - NAME=portal
      context: ./app
      dockerfile: Dockerfile.dev
    command: npm start
    depends_on:
      - api
    secrets:
      - localhost_ssl_cert
      - localhost_ssl_key
      - ca_cert

volumes:
  dev-db-data:


secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  stripe_webhook_secret:
    file: ./secrets/stripe_webhook_secret
  stripe_api_key:
    file: ./secrets/stripe_api_key
  django_secret_key:
    file: ./secrets/django_secret_key
  # SSL certs
  ledget_ssl_cert:
    file: ./secrets/certs/ledget.app.crt
  ledget_ssl_key:
    file: ./secrets/certs/ledget.app.key
  localhost_ssl_cert:
    file: ./secrets/certs/localhost.crt
  localhost_ssl_key:
    file: ./secrets/certs/localhost.key
  ca_cert:
    file: ./secrets/certs/ledgetCA.pem
