version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
  redis:
    image: redis:7.2.1-alpine
  ledgetback:
    build:
      args:
        - DEV=true
      context: ./back
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SILK_DEBUG=true
    secrets:
      - django_secret_key
      - postgres_user
      - postgres_password
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
volumes:
  dev-db-data:


secrets:
  postgres_user:
    file: ./test_secrets/postgres_user
  postgres_password:
    file: ./test_secrets/postgres_password
  django_secret_key:
    file: ./test_secrets/django_secret_key
