version: '3.8'

services:
  ledgetapi:
    build:
      args:
        - DEV=true
      context: ./ledgetapi
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py runserver"
    depends_on:
      - db
    env_file:
      - ./ledgetapi/.env.dev
    environment:
      LEDGET_DB: devdb
      LEDGET_DB_USER: dbuser
      LEDGET_DB_PASSWORD: dbpassword
      LEDGET_DB_HOST: db
      LEDGET_DB_PORT: 5432
    volumes:
      - ./certs:/certs
      - ./logs:/ledgetapi/logs
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
volumes:
  dev-db-data:
  certs:
  logs:
