version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  oathkeeper:
    build:
      args:
        - API_VERSION=1
      context: ./oathkeeper
    entrypoint: oathkeeper
    command: serve --config /etc/config/oathkeeper/config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oathkeeper.rule=Host(`oathkeeper`)"
      - "traefik.http.routers.oathkeeper.entrypoints=web"
      - "traefik.http.routers.oathkeeper.service=oathkeeper"
      - "traefik.http.services.oathkeeper.loadbalancer.server.port=4456"
      - "traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions"
      - "traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-Device-Token, Authorization, X-Session-Token"
      - "traefik.http.middlewares.oathkeeper.forwardauth.authRequestHeaders=X-Device-Token, Authorization"
    secrets:
      - jwks.json
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # ^^ needed so that we can check ip address of the ory webhook response in the django middleware
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/traefik"
      - "--providers.file.watch=true"
      - "--log.level=DEBUG"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./front/certs:/etc/ssl/certs
      - ./traefik:/traefik
      - /var/run/docker.sock:/var/run/docker.sock
  restapi:
    build:
      args:
        - VERSION=1
        - ENVIRONMENT=dev
      context: ./back
    labels:
      - "traefik.enable=true"
      # Middleware
      - "traefik.http.middlewares.hooksIpWhitelist.ipwhitelist.sourcerange=3.18.12.63, 3.130.192.231, 13.235.14.237, 13.235.122.149, 18.211.135.69, 35.154.171.200, 52.15.183.38, 54.88.130.119, 54.88.130.237, 54.187.174.169, 54.187.205.235, 54.187.216.72, 34.22.170.75, 35.242.228.133, 52.21.26.131, 52.21.47.157, 52.41.247.19, 52.88.82.239"
      - "traefik.http.middlewares.hooksIpWhitelist.ipwhitelist.ipstrategy.depth=1"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=https://localhost:3000, https://localhost:3001, https://localhost, https://10.0.2.2"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type, X-CsrfToken"
      - "traefik.http.middlewares.cors.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.cors.headers.addVaryHeader=true"

      # Silk router
      - "traefik.http.routers.silk.rule=(Host(`localhost`))"
      - "traefik.http.routers.silk.entrypoints=web"

      # Health router
      - "traefik.http.routers.health.rule=((Host(`10.0.2.2`) || Host(`localhost`))  && PathPrefix(`/health`))"
      - "traefik.http.routers.health.entrypoints=websecure"
      - "traefik.http.routers.health.tls=true"
      - "traefik.http.routers.health.middlewares=cors@docker, oathkeeper"
      # API router
      - "traefik.http.routers.api.rule=((Host(`10.0.2.2`) || Host(`localhost`)) && PathPrefix(`/v{version:[0-9]+}/`))"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.middlewares=cors@docker, oathkeeper"
      # Hooks router
      - "traefik.http.routers.hooks.rule=(HostRegexp(`localhost`) && PathPrefix(`/hooks`))"
      - "traefik.http.routers.hooks.entrypoints=websecure"
      - "traefik.http.routers.hooks.tls=true"
      - "traefik.http.routers.hooks.middlewares=hooksIpWhitelist@docker"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - DEBUG=true
      - SILK_DEBUG=true
      - PLAID_ENV=Sandbox
    volumes:
      - ./back/restapi:/restapi
    secrets:
      - stripe_webhook_secret
      - stripe_api_key
      - ory_hook_api_key
      - ory_api_key
      - django_secret_key
      - postgres_user
      - postgres_password
      - plaid_api_key
      - plaid_sand_api_key
      - plaid_client_id
      - sparkpost_api_key
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8000:8000
  celery:
    build:
      context: ./back
    entrypoint: sh -c "/restapi/celery_startup.sh"
    volumes:
      - ./back/restapi:/restapi
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
      - PLAID_ENV=Sandbox
      - ENVIRONMENT=dev
    depends_on:
      - rabbitmq
      - restapi
    secrets:
      - ory_api_key
      - plaid_api_key
      - plaid_sand_api_key
      - postgres_user
      - postgres_password
      - plaid_client_id
  ory:
    image: oryd/ory:v0.3
    ports:
      - 4000:4000
    secrets:
      - ory_tunnel_key
    entrypoint: ''
    command: >
      sh -c "
        export ORY_API_KEY=$$(cat /run/secrets/ory_tunnel_key) &&
        ory tunnel --project reverent-lewin-bqqp1o2zws --allowed-cors-origins https://localhost:3000 https://localhost:3001 https://10.0.2.2"
volumes:
  dev-db-data:
  doker-events:


secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  sparkpost_api_key:
    file: ./secrets/sparkpost_api_key
  stripe_webhook_secret:
    file: ./secrets/stripe_webhook_secret
  stripe_api_key:
    file: ./secrets/stripe_api_key
  plaid_api_key:
    file: ./secrets/plaid_dev_api_key
  plaid_client_id:
    file: ./secrets/plaid_client_id
  plaid_sand_api_key:
    file: ./secrets/plaid_sand_api_key
  django_secret_key:
    file: ./secrets/django_secret_key
  ory_hook_api_key:
    file: ./secrets/ory_hook_api_key
  ory_api_key:
    file: ./secrets/ory_api_key
  ory_tunnel_key:
    file: ./secrets/ory_tunnel_key
  jwks.json:
    file: ./secrets/oathkeeper_jwks.json
