version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  restapi:
    build:
      args:
        - ENV=dev
        - VERSION=1
      context: ./back
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - DEBUG=true
      - PLAID_ENV=sandbox
    secrets:
      - django_secret_key
      - postgres_user
      - postgres_password
      - stripe_api_key
      - plaid_sand_api_key
      - ory_hook_api_key
      - plaid_client_id
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8000:8000
volumes:
  dev-db-data:


secrets:
  postgres_user:
    file: ./test_secrets/postgres_user
  postgres_password:
    file: ./test_secrets/postgres_password
  django_secret_key:
    file: ./test_secrets/django_secret_key
  stripe_api_key:
    file: ./test_secrets/stripe_api_key
  plaid_sand_api_key:
    file: ./test_secrets/plaid_sand_api_key
  ory_hook_api_key:
    file: ./test_secrets/ory_hook_api_key
  plaid_client_id:
    file: ./test_secrets/plaid_client_id
