version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
  api:
    build:
      args:
        - DEV=true
      context: ./back
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runsslserver --cert /run/secrets/ledget_crt --key /run/secrets/ledget_key"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
    secrets:
      - stripe_webhook_secret
      - stripe_api_key
      - django_secret_key
      - postgres_user
      - postgres_password
      - ledget_crt
      - ledget_key
    volumes:
      - ./logs:/api/logs
    depends_on:
      - db
  proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - doker-events:/var/run/docker.sock:/var/run/docker.sock
  stripe-listener:
    image: stripe/stripe-cli
    env_file:
      - ./secrets/.env.stripe.dev
    command: listen --forward-to https://ledget.app:8000/api/v1/stripe-hook --skip-verify
    secrets:
      - stripe_api_key
  app:
    build:
      args:
        - APP=home
        - PORT=3000
      context: ./app
      dockerfile: Dockerfile.dev
    secrets:
      - localhost_key
      - localhost_crt
      - ledget_ca_pem
    ports:
      - 3000:3000
  portal:
    build:
      args:
        - APP=portal
        - PORT=3001
      context: ./app
      dockerfile: Dockerfile.dev
    secrets:
      - localhost_key
      - localhost_crt
      - ledget_ca_pem
    ports:
      - 3001:3001
  ory:
    build:
      context: ./ory
    ports:
      - "4000:4000"
    command: >
      sh -c "
        /orylogin.sh /run/secrets/ory_email /run/secrets/ory_password &&
        ory tunnel --dev --project reverent-lewin-bqqp1o2zws https://localhost:3000"
    secrets:
      - ory_email
      - ory_password

volumes:
  dev-db-data:
  doker-events:


secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  stripe_webhook_secret:
    file: ./secrets/stripe_webhook_secret
  stripe_api_key:
    file: ./secrets/stripe_api_key
  django_secret_key:
    file: ./secrets/django_secret_key
  ledget_crt:
    file: ./secrets/certs/ledget.app.crt
  ledget_key:
    file: ./secrets/certs/ledget.app.key
  localhost_crt:
    file: ./secrets/certs/localhost.crt
  localhost_key:
    file: ./secrets/certs/localhost.key
  ledget_ca_pem:
    file: ./secrets/certs/ledgetCA.pem
  ory_email:
    file: ./secrets/ory_email
  ory_password:
    file: ./secrets/ory_password
