version: '3.8'

services:
  ledgetapi:
    build:
      args:
        - DEV=true
      context: ./ledgetapi
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver"
    depends_on:
      - db
    env_file:
      - ./ledgetapi/.env.dev
      - ./ledgetapi/.env.stripe.dev
    environment:
      LEDGET_DB: devdb
      LEDGET_DB_USER: dbuser
      LEDGET_DB_PASSWORD: dbpassword
      LEDGET_DB_HOST: db
      LEDGET_DB_PORT: 5432
    volumes:
      - ./certs:/certs
      - ./logs:/ledgetapi/logs
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
  stripe-listener:
    image: stripe/stripe-cli
    env_file:
      - ./ledgetapi/.env.stripe.dev
    command: |
      listen --forward-to https://ledget.app:8000/api/v1/stripe-hook --skip-verify
  ory-tunnel:
    build:
      context: git@github.com:ory/cli.git
      dockerfile: .docker/Dockerfile-alpine
    ports:
      - "4000:4000"
volumes:
  dev-db-data:
  certs:
  logs:
