version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - dev-db-data:/var/lib/postgresql/data/
  api:
    build:
      args:
        - DEV=true
      context: ./back
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runsslserver --cert /etc/ssl/certs/ledget.app.crt --key /etc/ssl/certs/ledget.app.key"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_PORT=5432
    volumes:
      - ./certs/ledget.app.crt:/etc/ssl/certs/ledget.app.crt
      - ./certs/ledget.app.key:/etc/ssl/certs/ledget.app.key
      - ./logs:/api/logs
    secrets:
      - stripe_webhook_secret
      - stripe_api_key
      - django_secret_key
      - postgres_user
      - postgres_password
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`ledget.app`) && PathPrefix(`/api`)
      - traefik.http.routers.api.tls=true
      - traef.http.routers.api.middlewares=oathkeeper
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=./certs"
      - "--providers.file.watch=true"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    labels:
      - traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions
      - traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-Id-Token,Authorization
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - doker-events:/var/run/docker.sock:/var/run/docker.sock
  oathkeeper:
    build:
      context: ./oathkeeper
    command: serve --config /config.yml
    labels:
      - traefik.http.routers.oathkeeper.entrypoints=web
      - traefik.http.routers.oathkeeper.rule=Host(`oathkeeper`)
      - traefik.http.services.oathkeeper.loadbalancer.server.port=4456
  app:
    build:
      args:
        - APP=home
        - PORT=3000
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./app/home:/home
      - ./certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./certs/localhost.key:/etc/ssl/certs/localhost.key
      - ./certs/ledgetCA.pem:/etc/ssl/certs/ledgetCA.pem
  portal:
    build:
      args:
        - APP=portal
        - PORT=3001
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    stdin_open: true
    volumes:
      - ./app/portal:/portal
      - ./certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./certs/localhost.key:/etc/ssl/certs/localhost.key
      - ./certs/ledgetCA.pem:/etc/ssl/certs/ledgetCA.pem
  ory:
    build:
      context: ./ory
    ports:
      - "4000:4000"
    command: >
      sh -c "
        /orylogin.sh /run/secrets/ory_email /run/secrets/ory_password &&
        ory tunnel --dev --project reverent-lewin-bqqp1o2zws https://localhost:3000"
    secrets:
      - ory_email
      - ory_password

volumes:
  dev-db-data:
  doker-events:


secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  stripe_webhook_secret:
    file: ./secrets/stripe_webhook_secret
  stripe_api_key:
    file: ./secrets/stripe_api_key
  django_secret_key:
    file: ./secrets/django_secret_key
  ory_email:
    file: ./secrets/ory_email
  ory_password:
    file: ./secrets/ory_password
