cookies:
  domain: reverent-lewin-bqqp1o2zws.projects.oryapis.com
  path: /
  same_site: Lax
courier:
  smtp:
    from_name: ledget via Ory
  templates:
    recovery:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    recovery_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
    verification_code:
      invalid:
        email:
          body: {}
      valid:
        email:
          body: {}
feature_flags:
  cacheable_sessions: false
identity:
  default_schema_id: 0a6ec3dda66dbf64a8274fd8da74139243ad7e3004949f535b72d62754858d98ddbe057d886ab602e0d2555e2e8ac78d8f3cb7a9c6294e40fb5983762a855651
  schemas:
  - id: preset://username
    url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9pZGVudGl0eS51c2VybmFtZS5zY2hlbWEuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwKICAidGl0bGUiOiAiUGVyc29uIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJwcm9wZXJ0aWVzIjogewogICAgInRyYWl0cyI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgInVzZXJuYW1lIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJ0aXRsZSI6ICJVc2VybmFtZSIsCiAgICAgICAgICAibWF4TGVuZ3RoIjogMTAwLAogICAgICAgICAgIm9yeS5zaC9rcmF0b3MiOiB7CiAgICAgICAgICAgICJjcmVkZW50aWFscyI6IHsKICAgICAgICAgICAgICAicGFzc3dvcmQiOiB7CiAgICAgICAgICAgICAgICAiaWRlbnRpZmllciI6IHRydWUKICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICJ3ZWJhdXRobiI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgInRvdHAiOiB7CiAgICAgICAgICAgICAgICAiYWNjb3VudF9uYW1lIjogdHJ1ZQogICAgICAgICAgICAgIH0KICAgICAgICAgICAgfQogICAgICAgICAgfQogICAgICAgIH0KICAgICAgfSwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJ1c2VybmFtZSIKICAgICAgXSwKICAgICAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogZmFsc2UKICAgIH0KICB9Cn0K
  - id: preset://email
    url: base64://ewogICIkaWQiOiAiaHR0cHM6Ly9zY2hlbWFzLm9yeS5zaC9wcmVzZXRzL2tyYXRvcy9pZGVudGl0eS5lbWFpbC5zY2hlbWEuanNvbiIsCiAgIiRzY2hlbWEiOiAiaHR0cDovL2pzb24tc2NoZW1hLm9yZy9kcmFmdC0wNy9zY2hlbWEjIiwKICAidGl0bGUiOiAiUGVyc29uIiwKICAidHlwZSI6ICJvYmplY3QiLAogICJwcm9wZXJ0aWVzIjogewogICAgInRyYWl0cyI6IHsKICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgImVtYWlsIjogewogICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICJmb3JtYXQiOiAiZW1haWwiLAogICAgICAgICAgInRpdGxlIjogIkUtTWFpbCIsCiAgICAgICAgICAib3J5LnNoL2tyYXRvcyI6IHsKICAgICAgICAgICAgImNyZWRlbnRpYWxzIjogewogICAgICAgICAgICAgICJwYXNzd29yZCI6IHsKICAgICAgICAgICAgICAgICJpZGVudGlmaWVyIjogdHJ1ZQogICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgIndlYmF1dGhuIjogewogICAgICAgICAgICAgICAgImlkZW50aWZpZXIiOiB0cnVlCiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAidG90cCI6IHsKICAgICAgICAgICAgICAgICJhY2NvdW50X25hbWUiOiB0cnVlCiAgICAgICAgICAgICAgfQogICAgICAgICAgICB9LAogICAgICAgICAgICAicmVjb3ZlcnkiOiB7CiAgICAgICAgICAgICAgInZpYSI6ICJlbWFpbCIKICAgICAgICAgICAgfSwKICAgICAgICAgICAgInZlcmlmaWNhdGlvbiI6IHsKICAgICAgICAgICAgICAidmlhIjogImVtYWlsIgogICAgICAgICAgICB9CiAgICAgICAgICB9LAogICAgICAgICAgIm1heExlbmd0aCI6IDMyMAogICAgICAgIH0KICAgICAgfSwKICAgICAgInJlcXVpcmVkIjogWwogICAgICAgICJlbWFpbCIKICAgICAgXSwKICAgICAgImFkZGl0aW9uYWxQcm9wZXJ0aWVzIjogZmFsc2UKICAgIH0KICB9Cn0K
  - id: 3a9ac2f96923c4096f3a68702516b1836a189d87a7256256aac1f31b2e9f0179bf9f097d29028c2e88ba7cb29ff66c7f218f9a48a69883a5b637e672a5de2590
    url: https://storage.googleapis.com/bac-gcs-production/3a9ac2f96923c4096f3a68702516b1836a189d87a7256256aac1f31b2e9f0179bf9f097d29028c2e88ba7cb29ff66c7f218f9a48a69883a5b637e672a5de2590.json
  - id: 269b5cf35ab7230cba1bb89380eca75b257e55b664887fae12dafbcbc5d3bee67711707e9975c544671d7295bf73db017efed0c445a1c57cf5ea5899556b183e
    url: https://storage.googleapis.com/bac-gcs-production/269b5cf35ab7230cba1bb89380eca75b257e55b664887fae12dafbcbc5d3bee67711707e9975c544671d7295bf73db017efed0c445a1c57cf5ea5899556b183e.json
  - id: 7e67a027eb682fcd96c0d5f65973ccdbce9cb39327d454a0e136ed491d404e2a7172f52d2cb5be4d40a97e468d916b800394c7ba8e6bb5be46cfcb87c805e33b
    url: https://storage.googleapis.com/bac-gcs-production/7e67a027eb682fcd96c0d5f65973ccdbce9cb39327d454a0e136ed491d404e2a7172f52d2cb5be4d40a97e468d916b800394c7ba8e6bb5be46cfcb87c805e33b.json
  - id: 0a6ec3dda66dbf64a8274fd8da74139243ad7e3004949f535b72d62754858d98ddbe057d886ab602e0d2555e2e8ac78d8f3cb7a9c6294e40fb5983762a855651
    url: https://storage.googleapis.com/bac-gcs-production/0a6ec3dda66dbf64a8274fd8da74139243ad7e3004949f535b72d62754858d98ddbe057d886ab602e0d2555e2e8ac78d8f3cb7a9c6294e40fb5983762a855651.json
oauth2_provider:
  override_return_to: false
selfservice:
  allowed_return_urls:
  - https://reverent-lewin-bqqp1o2zws.projects.oryapis.com
  default_browser_return_url: /ui/welcome
  flows:
    error:
      ui_url: https://localhost:3000/error
    login:
      after:
        default_browser_return_url: https://localhost:3001/spending
        hooks: []
        oidc:
          hooks: []
        password:
          hooks: []
        webauthn:
          hooks: []
      before:
        hooks: []
      lifespan: 30m0s
      ui_url: https://localhost:3001/login
    logout:
      after: {}
    recovery:
      after:
        hooks: []
      before:
        hooks: []
      enabled: false
      lifespan: 30m0s
      notify_unknown_recipients: false
      ui_url: https://localhost:3001/recovery
      use: code
    registration:
      after:
        hooks:
          - hook: web_hook
            config:
              url: https://91da-2601-681-77e-21e0-e1db-979d-a7f2-8381.ngrok.io/hooks/ory
              method: POST
              body: base64://ZnVuY3Rpb24oY3R4KSB7IHVzZXJfaWQ6IGN0eC5pZGVudGl0eS5pZCB9
              response:
                ignore: false
                parse: false
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: "Api-Key TtID6VH26LxojJmoQdlnYu16yjwMWOK_RX615crDFyD2jy5AI6CbxOi5qBTonOVMx7mZmF4g6g9_3kTeplahEXO5jy7LC_hYLYo"
                  in: header
        oidc:
          hooks: []
        password:
          hooks: []
        webauthn: []
      before:
        hooks: []
      ui_url: https://localhost:3001/register
    settings:
      after:
        hooks: []
        password:
          hooks: []
        profile:
          hooks: []
      before:
        hooks: []
      lifespan: 30m0s
      privileged_session_max_age: 15m0s
      required_aal: highest_available
      ui_url: /ui/settings
    verification:
      after:
        default_browser_return_url: https://localhost:3000/spending
        hooks: []
      before:
        hooks: []
      enabled: false
      lifespan: 30m0s
      notify_unknown_recipients: false
      ui_url: https://localhost:3001/verification
      use: code
  methods:
    code:
      config:
        lifespan: 15m0s
      enabled: true
    link:
      config:
        base_url: ""
        lifespan: 15m0s
      enabled: true
    lookup_secret:
      enabled: false
    oidc:
      config:
        providers:
        - client_id: 845168344908-te17c2gpkq5qbajvmjamehhh75ejg4mq.apps.googleusercontent.com
          client_secret: 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
          id: google
          label: Google
          mapper_url: https://storage.googleapis.com/bac-gcs-production/906213ca252f250a85aabdb06ec6da8355ed0db768087a0fb63de66ab52dc1697ad77d198af0c0affe4ce8ea7006b66cfee32d64ad55c666b524e19cac7bf8db.jsonnet
          provider: google
          scope:
          - profile
          - email
        - client_id: "589779369930436"
          client_secret: bf247a4d0f50247d6ce3cbd9095fef3e
          id: facebook
          label: Facebook
          mapper_url: https://storage.googleapis.com/bac-gcs-production/3b51404cbcf5491b636f2b267aa24d3ddf9a75dc8e1457acd9b24efbd1f28135769644d00c7affa5d40e3d9f0e26439535d4dc6295b8dca97503582c2fac0901.jsonnet
          provider: facebook
          scope: []
      enabled: true
    password:
      config:
        haveibeenpwned_enabled: true
        identifier_similarity_check_enabled: true
        ignore_network_errors: true
        max_breaches: 1
        min_password_length: 8
      enabled: true
    profile:
      enabled: true
    totp:
      config:
        issuer: ledget
      enabled: false
    webauthn:
      config:
        passwordless: false
        rp:
          display_name: ledget
          id: reverent-lewin-bqqp1o2zws.projects.oryapis.com
          origin: https://reverent-lewin-bqqp1o2zws.projects.oryapis.com
      enabled: false
serve:
  admin:
    base_url: https://reverent-lewin-bqqp1o2zws.projects.oryapis.com/
    request_log:
      disable_for_health: true
  public:
    base_url: https://reverent-lewin-bqqp1o2zws.projects.oryapis.com/
    cors:
      enabled: false
    request_log:
      disable_for_health: true
session:
  cookie:
    domain: reverent-lewin-bqqp1o2zws.projects.oryapis.com
    name: ory_session_reverentlewinbqqp1o2zws
    path: /
    persistent: false
    same_site: Lax
  lifespan: 72h0m0s
  whoami:
    required_aal: highest_available
