# Generated by Django 4.2.4 on 2023-08-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
