# Generated by Django 4.2.4 on 2023-09-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
