# Generated by Django 4.2.4 on 2023-09-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_device_mfa_user_mfa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mfa',
            new_name='mfa_enabled',
        ),
    ]
