# Generated by Django 4.2.4 on 2023-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_mfa_enabled_user_authenticator_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authenticator_enabled_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
