# Generated by Django 4.2.4 on 2023-09-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_authenticator_enabled_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authenticator_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='authenticator_enabled_on',
        ),
    ]
