# Generated by Django 4.2.4 on 2023-09-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_device_location_alter_device_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='aal',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
