# Generated by Django 4.2.4 on 2023-09-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_device_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='authenticator_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_method',
            field=models.BooleanField(choices=[('authenticator', 'Authenticator'), ('email', 'Email'), ('phone', 'Phone')], default=None, null=True),
        ),
    ]
