# Generated by Django 4.2.4 on 2023-09-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_user_mfa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agent_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('pc', 'PC'), ('tablet', 'Tablet'), ('bot', 'Bot')], default=None, max_length=10, null=True),
        ),
    ]
