# Generated by Django 4.2.4 on 2023-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_authenticator_enabled_on_user_mfa_enabled_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_device',
            field=models.CharField(choices=[('totp', 'Authenticator'), ('email', 'Email'), ('sms', 'SMS')], default=None, null=True),
        ),
    ]
