# Generated by Django 4.2.4 on 2023-09-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_user_mfa_device_alter_user_mfa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
