# Generated by Django 4.2.4 on 2023-09-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('otp', 'OTP')], default='otp', max_length=4, null=True),
        ),
    ]
