# Generated by Django 4.2.4 on 2023-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_device_aal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='aal',
            field=models.CharField(choices=[('aal1', 'AAL1'), ('aal1.5', 'AAL1.5'), ('aal2', 'AAL2')], default='aal1', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('otp', 'OTP')], default=None, max_length=4, null=True),
        ),
    ]
