# Generated by Django 4.2.4 on 2023-09-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_last_otp_verification_alter_device_aal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('paused', 'Paused'), ('deleted', 'Deleted')], default=None, max_length=20, null=True),
        ),
    ]
