# Generated by Django 4.2.4 on 2023-10-01 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_customer_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canceled_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
