# Generated by Django 4.2.4 on 2023-10-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_phone_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
