# Generated by Django 4.2.4 on 2023-10-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_user_is_co_owner_user_yearly_categories_anchor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='yearly_categories_anchor',
            new_name='yearly_anchor',
        ),
    ]
