# Generated by Django 4.2.4 on 2024-04-26 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_user_last_otp_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cancelation_reason',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_flag',
        ),
        migrations.RemoveField(
            model_name='user',
            name='canceled_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_co_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yearly_anchor',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('yearly_anchor', models.DateTimeField(default=None, null=True)),
                ('flag', models.CharField(choices=[('service_abuse', 'Service abuse')], default=None, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Field must contain only letters and numbers.', regex='^[a-zA-Z0-9-]{15,}+$')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('canceled_on', models.DateTimeField(default=None, null=True)),
                ('feedback', models.CharField(default=None, max_length=1000, null=True)),
                ('cancelation_reason', models.CharField(default=None, max_length=1000, null=True)),
                ('customer', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
