# Generated by Django 4.2.4 on 2024-04-26 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_customer_cancelation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cancelation_reason',
        ),
        migrations.RemoveField(
            model_name='account',
            name='feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(default=None, max_length=1000, null=True)),
                ('cancelation_reason', models.CharField(default=None, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
