# Generated by Django 4.2.4 on 2024-04-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_country_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
