# Generated by Django 4.2.4 on 2024-05-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_user_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_test',
        ),
    ]
