# Generated by Django 4.2.4 on 2024-05-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_user_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='co_owner',
        ),
    ]
