# Generated by Django 4.2.4 on 2024-05-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_user_co_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.account'),
        ),
    ]
