# Generated by Django 4.2.4 on 2024-05-26 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_enabled_on',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_method',
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('automatic_logout', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(choices=[('totp', 'TOTP')], default=None, max_length=4, null=True)),
                ('mfa_enabled_on', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
