# Generated by Django 4.2.4 on 2024-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_remove_user_mfa_enabled_on_remove_user_mfa_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='automatic_logout',
            field=models.BooleanField(default=True),
        ),
    ]
