# Generated by Django 4.2.4 on 2025-03-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_settings_automatic_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
    ]
