# Generated by Django 4.1.7 on 2023-03-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_period',
            field=models.CharField(choices=[('M', 'Month'), ('Y', 'Year')], default='M', max_length=1),
        ),
    ]
