# Generated by Django 4.1.7 on 2023-03-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('core', '0002_user_is_subscriber_user_subscription_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            bases=('socialaccount.socialaccount',),
        ),
    ]
