# Generated by Django 4.1.7 on 2023-03-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customsocialaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSocialAccount',
        ),
    ]
