# Generated by Django 4.1.7 on 2023-03-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_is_subscriber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripeid',
            new_name='stripe_customer_id',
        ),
    ]
