# Generated by Django 4.1.7 on 2023-03-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_stripeid_customer_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
