# Generated by Django 4.1.7 on 2023-02-26 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
