# Generated by Django 4.1.7 on 2023-03-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
    ]
