# Generated by Django 4.2.2 on 2023-08-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mask', models.CharField(max_length=10)),
                ('subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(blank=True, null=True)),
                ('pending_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('iso_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('unnoficial_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('check_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('authorized_datetime', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=5, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('store_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.account')),
            ],
            options={
                'ordering': ['-date', '-datetime'],
                'get_latest_by': ['date', 'datetime'],
            },
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100, null=True)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financials.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financials_plaid_item',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='financials.institution'),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='financials.plaiditem'),
        ),
    ]
