# Generated by Django 4.2.2 on 2023-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='oath',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
    ]
