# Generated by Django 4.2.4 on 2023-08-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_alter_plaiditem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
