# Generated by Django 4.2.4 on 2023-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_alter_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='confirmed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
