# Generated by Django 4.2.4 on 2023-08-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0010_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
