# Generated by Django 4.2.4 on 2023-10-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0019_remove_account_order_transaction_bill_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bill_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
