# Generated by Django 4.2.4 on 2023-11-02 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_usercategory_options'),
        ('financials', '0020_alter_transaction_bill_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='wrong_predicted_bill',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wrong_predicted_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='predicted_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_bill', to='budget.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_category', to='budget.category'),
        ),
    ]
