# Generated by Django 4.2.4 on 2023-11-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_transactioncategory'),
        ('financials', '0022_remove_transaction_bill_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='transactions', through='budget.TransactionCategory', to='budget.category'),
        ),
    ]
