# Generated by Django 4.2.4 on 2024-04-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0027_useraccount_primary_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='pending_expired',
            field=models.BooleanField(default=False),
        ),
    ]
