# Generated by Django 4.2.4 on 2024-05-10 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0029_remove_useraccount_primary_owner_account_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
