# Generated by Django 4.2.4 on 2024-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0030_institution_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
