# Generated by Django 4.2.4 on 2024-05-12 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0031_plaiditem_last_synced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaiditem',
            old_name='pending_expired',
            new_name='pending_expiration',
        ),
    ]
