# Generated by Django 4.2.4 on 2024-05-19 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0032_rename_pending_expired_plaiditem_pending_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plaid_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='financials.plaiditem'),
        ),
    ]
