# Generated by Django 4.2.4 on 2024-09-10 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0034_alter_plaiditem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plaid_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='financials.plaiditem'),
        ),
    ]
