# Generated by Django 4.2.4 on 2024-09-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_default_reminder_data'),
        ('financials', '0035_change_account_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', through='budget.TransactionCategory', to='budget.category'),
        ),
    ]
