# Generated by Django 4.2.4 on 2024-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0037_alter_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cardHue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
