# Generated by Django 4.2.4 on 2024-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0041_alter_accountbalance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='investments_supported',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='liabilities_supported',
            field=models.BooleanField(null=True),
        ),
    ]
