# Generated by Django 4.2.4 on 2024-10-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0042_plaiditem_investments_supported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaiditem',
            name='investments_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plaiditem',
            name='liabilities_supported',
            field=models.BooleanField(default=True),
        ),
    ]
