# Generated by Django 4.2.4 on 2024-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0043_alter_plaiditem_investments_supported_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_spend',
        ),
        migrations.AddField(
            model_name='transaction',
            name='detail',
            field=models.CharField(blank=True, choices=[('0', 'income'), ('1', 'investment_transfer_out'), ('2', 'spending')], null=True),
        ),
    ]
