# Generated by Django 4.2.4 on 2024-11-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0045_alter_transaction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='detail',
            field=models.IntegerField(blank=True, choices=[(0, 'income'), (1, 'investment_transfer_out'), (2, 'spending')], null=True),
        ),
    ]
