# Generated by Django 4.2.4 on 2025-01-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0046_alter_transaction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
