# Generated by Django 4.2.4 on 2025-01-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0048_holdingpin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='cardHue',
            new_name='card_hue',
        ),
    ]
