# Generated by Django 4.2.4 on 2025-01-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0049_rename_cardhue_useraccount_card_hue'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pinned',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
