# Generated by Django 4.2.4 on 2025-01-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0050_useraccount_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='pinned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
