# Generated by Django 4.1.7 on 2023-04-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_city_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delinquet',
            field=models.BooleanField(default=False),
        ),
    ]
