# Generated by Django 4.1.7 on 2023-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_delinquet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='signup_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='created',
            field=models.IntegerField(default=1677945900, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_start',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
