# Generated by Django 4.1.7 on 2023-04-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_city_remove_user_state_remove_user_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
