# Generated by Django 4.1.7 on 2023-04-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_billinginfo_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_subscription_id',
            new_name='subscription_id',
        ),
    ]
