# Generated by Django 4.1.7 on 2023-04-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_customer_signup_date_subscription_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='delinquet',
            new_name='delinquent',
        ),
    ]
