# Generated by Django 4.1.7 on 2023-04-05 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_stripe_customer_id_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
