# Generated by Django 4.1.7 on 2023-04-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_subscription_trial_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provision_service',
            field=models.BooleanField(default=False),
        ),
    ]
