# Generated by Django 4.1.7 on 2023-04-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_account_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service_expiration',
        ),
    ]
