# Generated by Django 4.1.7 on 2023-04-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_price_livemode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_payment_method',
        ),
        migrations.AddField(
            model_name='customer',
            name='service_expires',
            field=models.IntegerField(default=0),
        ),
    ]
