# Generated by Django 4.1.7 on 2023-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_customer_default_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='service_expires',
        ),
        migrations.AddField(
            model_name='customer',
            name='service_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
