# Generated by Django 4.1.7 on 2023-04-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_customer_service_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='livemode',
            field=models.BooleanField(default=False),
        ),
    ]
