# Generated by Django 4.1.7 on 2023-04-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_price_livemode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='service_provisioned',
        ),
        migrations.AddField(
            model_name='customer',
            name='service_expiration',
            field=models.IntegerField(default=0),
        ),
    ]
