# Generated by Django 4.1.7 on 2023-04-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_customer_service_provisioned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client_secret',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
