# Generated by Django 4.1.7 on 2023-04-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_subscription_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'trialing'), ('active', 'active'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('past_due', 'past_due'), ('unpaid', 'unpaid'), ('canceled', 'canceled')], max_length=20),
        ),
    ]
