# Generated by Django 4.1.7 on 2023-04-13 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delinquent',
        ),
    ]
