# Generated by Django 4.1.7 on 2023-04-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_customer_delinquent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.price'),
        ),
    ]
