# Build Stage
FROM node:lts-bullseye-slim AS build

ARG APP

COPY ./"$APP"/package*.json .
RUN npm ci --only=production
RUN npm install --only=development

# Runtime
FROM node:lts-bullseye-slim AS production

ARG APP
WORKDIR /"$APP"
COPY --from=build /node_modules ./node_modules
COPY ./"$APP"/ .

ARG PORT
EXPOSE "$PORT"
CMD ["vite", "start"]
