FROM node:14-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

ARG DEV
RUN if [ "$DEV" = "true" ]; then npm install; fi
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
