# Generated by Django 4.1.7 on 2023-04-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_delinquet_customer_delinquent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
