# Generated by Django 4.1.7 on 2023-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_subscription_client_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='client_secret',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created',
            field=models.IntegerField(default=12321, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('trialing', 'trialing'), ('active', 'active'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('unpaid', 'unpaid')], default=123123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_start',
            field=models.IntegerField(default=132213, editable=False),
            preserve_default=False,
        ),
    ]
