# Generated by Django 4.1.7 on 2023-04-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_price_renews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.IntegerField(default=1, editable=False, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_end',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
