# Generated by Django 4.1.7 on 2023-04-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_subscription_client_secret_customer_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.IntegerField(editable=False),
        ),
    ]
