# Generated by Django 4.2.2 on 2023-08-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField(blank=True, null=True)),
                ('pending_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('iso_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('unnoficial_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('check_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('authorized_datetime', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('store_number', models.CharField(blank=True, max_length=10, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.account')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
