# Generated by Django 4.2.2 on 2023-08-12 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_plaiditem_table'),
        ('institutions', '0003_account_transactions_delete_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'get_latest_by': ['date', 'datetime'], 'ordering': ['-date', '-datetime']},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(default='oQedoXE1vquvnNzgGzBbs8vrQoPjnNtRAXjXj', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.plaiditem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='mask',
            field=models.CharField(default='0000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='asdfjweoifjfe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='aewoifjweiojewej', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='region',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='store_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
