# Generated by Django 4.2.2 on 2023-08-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mask',
            field=models.CharField(max_length=10),
        ),
    ]
