# Generated by Django 4.2.2 on 2023-08-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_account_mask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactions',
            table=None,
        ),
    ]
