# Generated by Django 4.2.2 on 2023-08-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='budget_alert',
        ),
    ]
