# Generated by Django 4.2.2 on 2023-08-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_alert_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='limit',
            new_name='limit_amount',
        ),
    ]
