# Generated by Django 4.2.2 on 2023-08-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_rename_limit_budgetcategory_limit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcategory',
            name='user',
        ),
    ]
