# Generated by Django 4.2.2 on 2023-08-10 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_remove_budgetcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='user',
            field=models.OneToOneField(default='1977dda5-be39-4a58-9c58-ab1d74eb2027', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
