# Generated by Django 4.2.2 on 2023-08-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetcategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetcategory',
            name='user',
        ),
    ]
