# Generated by Django 4.2.4 on 2023-10-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_bill_emoji_alter_category_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
