# Generated by Django 4.2.2 on 2023-08-10 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0009_remove_budgetcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='user',
            field=models.ForeignKey(default='0c4785f7-65a5-4420-8479-980399c64082', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
