# Generated by Django 4.2.2 on 2023-08-10 23:39

import budget.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0010_budgetcategory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget.budgetcategory'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('type', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], default='month', max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=10)),
                ('lower_amount', models.IntegerField(blank=True, null=True)),
                ('upper_amount', models.IntegerField()),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Day must be between 1 and 31.'), django.core.validators.MaxValueValidator(31, message='Day must be between 1 and 31.')])),
                ('day_of_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Day must be between 0 and 6.'), django.core.validators.MaxValueValidator(6, message='Day must be between 0 and 6.')])),
                ('week_number', models.IntegerField(blank=True, null=True, validators=[budget.models.validate_week_number])),
                ('month_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Day must be between 1 and 12.'), django.core.validators.MaxValueValidator(12, message='Day must be between 1 and 12.')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
