# Generated by Django 4.2.2 on 2023-08-11 15:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_alert_category_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='day_of_month',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='month_number',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='week_number',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='day_of_week',
            new_name='week_day',
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('day', 'Day'), ('week', 'Week')], default='week', max_length=40)),
                ('offset', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='budget.bill')),
            ],
            options={
                'db_table': 'budget_reminder',
            },
        ),
    ]
