# Generated by Django 4.2.2 on 2023-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_rename_day_of_month_bill_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('pending', models.BooleanField()),
                ('pending_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('iso_currency_code', models.CharField(max_length=3)),
                ('unnoficial_currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('check_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('authorized_datetime', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('store_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
