# Generated by Django 4.2.2 on 2023-08-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
