# Generated by Django 4.2.4 on 2023-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
