# Generated by Django 4.2.4 on 2023-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_category_deletable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deletable',
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
