# Generated by Django 4.2.4 on 2023-11-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_remove_category_deletable_category_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
