# Generated by Django 4.2.4 on 2023-11-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_bill_is_active_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.AddField(
            model_name='bill',
            name='removed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='removed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
