# Generated by Django 4.2.4 on 2023-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_remove_bill_is_active_remove_category_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
