# Generated by Django 4.2.4 on 2023-11-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_bill_skipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='bill',
        ),
    ]
