# Generated by Django 4.2.4 on 2023-11-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_remove_reminder_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='reminders',
            field=models.ManyToManyField(blank=True, related_name='bills', to='budget.reminder'),
        ),
    ]
