branch-defaults:
  default:
    environment: celery-worker-prod
environment-defaults:
  restapi-prod:
    branch: null
    repository: null
global:
  application_name: ledget-restapi
  default_ec2_keyname: ledget-restapi
  default_platform: Python 3.11
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
