# Generated by Django 4.2.4 on 2023-08-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_category_options_alter_category_table'),
        ('financials', '0007_transactions_confirmed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.bill'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
    ]
