# Generated by Django 4.2.4 on 2023-08-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_transactions_bill_transactions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='cursor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
