# Generated by Django 4.2.4 on 2023-08-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_category_options_alter_category_table'),
        ('financials', '0009_plaiditem_cursor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
