# Generated by Django 4.2.4 on 2023-08-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0011_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaiditem',
            name='cursor',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
