# Generated by Django 4.2.4 on 2023-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_plaiditem_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='new_account_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plaiditem',
            name='permission_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
