# Generated by Django 4.2.4 on 2023-09-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_plaiditem_new_account_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaiditem',
            old_name='new_account_available',
            new_name='new_accounts_available',
        ),
    ]
