# Generated by Django 4.2.4 on 2023-10-18 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0019_useraccountthroughmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ManyToManyField(through='financials.UserAccountThroughModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
