# Generated by Django 4.2.4 on 2023-10-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0020_account_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccountthroughmodel',
            options={'ordering': ('user', 'order')},
        ),
    ]
