# Generated by Django 4.2.4 on 2023-10-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0021_alter_useraccountthroughmodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccountthroughmodel',
            table='financials_user_account',
        ),
    ]
