# Generated by Django 4.2.4 on 2023-11-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0021_remove_transaction_wrong_predicted_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bill_confirmed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_confirmed',
        ),
    ]
