# Generated by Django 4.2.4 on 2023-10-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0022_alter_useraccountthroughmodel_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='users',
        ),
    ]
