# Generated by Django 4.2.4 on 2023-10-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0023_rename_user_account_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='order',
        ),
    ]
