# Generated by Django 4.2.4 on 2023-10-19 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0024_remove_account_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financials.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financials_user_account',
                'ordering': ('order',),
                'unique_together': {('account', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='UserAccountThroughModel',
        ),
        migrations.AlterField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(related_name='accounts', through='financials.UserAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
