# Generated by Django 4.2.4 on 2023-10-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0024_remove_account_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccountthroughmodel',
            options={'ordering': ('account', 'order')},
        ),
    ]
