# Generated by Django 4.2.4 on 2023-11-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0024_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
