# Generated by Django 4.2.4 on 2023-12-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0025_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_spend',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
