# Generated by Django 4.2.4 on 2023-10-18 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0025_alter_useraccountthroughmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccountthroughmodel',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='useraccountthroughmodel',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='useraccountthroughmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useraccountthroughmodel',
            unique_together={('account', 'user')},
        ),
        migrations.AlterModelTable(
            name='useraccountthroughmodel',
            table=None,
        ),
    ]
