# Generated by Django 4.2.4 on 2023-10-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0025_useraccount_delete_useraccountthroughmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
