# Generated by Django 4.2.4 on 2023-10-18 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financials', '0026_alter_useraccountthroughmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountthroughmodel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccountthroughmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='useraccountthroughmodel',
            table='financials_user_account',
        ),
    ]
