# Generated by Django 4.2.4 on 2023-10-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0026_transaction_custom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='custom_name',
            new_name='preferred_name',
        ),
    ]
