# Generated by Django 4.2.4 on 2023-10-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_bill_emoji_alter_category_emoji'),
        ('financials', '0027_rename_custom_name_transaction_preferred_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='predicted_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_transactions', to='budget.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_transactions', to='budget.category'),
        ),
    ]
