# Generated by Django 4.2.4 on 2023-10-20 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_category_limit_amount'),
        ('financials', '0028_transaction_predicted_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='predicted_bill',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='predicted_category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bill_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wrong_predicted_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrong_predicted_bill', to='budget.bill'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wrong_predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrong_predicted_category', to='budget.category'),
        ),
    ]
