# Generated by Django 4.2.4 on 2023-10-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0031_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
