# Generated by Django 4.1.7 on 2023-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.CharField(editable=False, max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(editable=False, max_length=70, primary_key=True, serialize=False),
        ),
    ]
