# Generated by Django 4.1.7 on 2023-04-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscription_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='current_period_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='default_payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
