# Generated by Django 4.1.7 on 2023-04-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_subscription_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='renews',
            field=models.CharField(default='monthly', max_length=20),
        ),
    ]
