# Generated by Django 4.1.7 on 2023-04-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_end',
            field=models.IntegerField(null=True),
        ),
    ]
