# Generated by Django 4.1.7 on 2023-04-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customer_default_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revoke_service_reason',
            field=models.CharField(choices=[('', 'No reason'), ('not_paid', 'Not paid'), ('service_abuse', 'Service abuse')], default=None, max_length=20, null=True),
        ),
    ]
