# Generated by Django 4.1.7 on 2023-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_revoke_service_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='revoke_service_reason',
        ),
        migrations.AddField(
            model_name='user',
            name='account_flag',
            field=models.CharField(choices=[('not_paid', 'Not paid'), ('payment_decline', 'Payment decline'), ('service_abuse', 'Service abuse')], default=None, max_length=20, null=True),
        ),
    ]
