# Generated by Django 4.1.7 on 2023-04-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_user_revoke_service_reason_user_account_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provision_service',
        ),
        migrations.AddField(
            model_name='user',
            name='service_expiration',
            field=models.IntegerField(default=0),
        ),
    ]
