# Generated by Django 4.1.7 on 2023-04-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_user_service_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='livemode',
        ),
    ]
