# Generated by Django 4.1.7 on 2023-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_subscription_customer_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_start',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
