global:
  checknewversion: true
  sendanonymoususage: true
api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":8000"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
  https:
    address: ":8443"

certificatesResolvers:

providers:
  docker:
    watch: true
    network: "traefik_proxy"
