# Build Stage
FROM node:20-slim AS base
ENV PNPM_HOME="/pmpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN corepack enable
COPY . /front
WORKDIR /front

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --froze
RUN pnpm run build

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=prod-deps /front/node_modules /front/node_modules
COPY --from=build /front/dist /app/dist

EXPOSE 3000
EXPOSE 3001

CMD ["npx", "nx", "serve", "webhome" "&&", "npx", "nx", "serve", "webportal"]
