FROM debian:12-slim

RUN apt-get update && \
    apt-get install -y curl && \
    apt-get install -y expect

RUN curl -o install.sh https://raw.githubusercontent.com/ory/meta/master/install.sh
RUN chmod +x install.sh
RUN ./install.sh ory

COPY ./orylogin.sh .
RUN chmod +x orylogin.sh

EXPOSE 4000
