NOT_SPEND_DETAILED = [
    'TRANSFER_IN_ACCOUNT_TRANSFER',
    'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT',
    'TRANSFER_IN_CASH_ADVANCES_AND_LOANS',
    'TRANSFER_IN_DEPOSIT',
    'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS',
    'TRANSFER_IN_SAVINGS',
    'TRANSFER_IN_OTHER_TRANSFER_IN',
    'TRANSFER_OUT_SAVINGS',
]

IS_INVESTMENTS_DETAIL = [
    'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS',
]

IS_INCOME_DETAIL = [
  'TRANSFER_IN_CASH_ADVANCES_AND_LOANS',
  'TRANSFER_IN_DEPOSIT',
]
