from rest_framework import serializers


class StudentLoanSerializer(serializers.Serializer):
    account_id = serializers.CharField()
    product_not_supported = serializers.BooleanField(required=False)
    account_number = serializers.CharField(required=False)
    disbursement_dates = serializers.ListField(required=False)
    expected_payoff_date = serializers.DateField(required=False)
    guarantor = serializers.CharField(required=False)
    interest_rate_percentage = serializers.FloatField(required=False)
    is_overdue = serializers.BooleanField(required=False)
    last_payment_amount = serializers.FloatField(required=False)
    last_payment_date = serializers.DateField(required=False)
    last_statement_balance = serializers.FloatField(required=False)
    last_statement_issue_date = serializers.DateField(required=False)
    loan_name = serializers.CharField(required=False)
    loan_status = serializers.DictField(required=False)
    minimum_payment_amount = serializers.FloatField(required=False)
    next_payment_due_date = serializers.DateField(required=False)
    origination_date = serializers.DateField(required=False)
    origination_principal_amount = serializers.FloatField(required=False)
    outstanding_interest_amount = serializers.FloatField(required=False)
    payment_reference_number = serializers.CharField(required=False)
    pslf_status = serializers.DictField(required=False)
    repayment_plan = serializers.DictField(required=False)
    sequence_number = serializers.CharField(required=False)
    servicer_address = serializers.DictField(required=False)
    ytd_interest_paid = serializers.FloatField(required=False)
    ytd_principal_paid = serializers.FloatField(required=False)


class MortgageSerializer(serializers.Serializer):
    account_id = serializers.CharField()
    product_not_supported = serializers.BooleanField(required=False)
    account_number = serializers.CharField(required=False)
    disbursement_dates = serializers.ListField(required=False)
    expected_payoff_date = serializers.DateField(required=False)
    guarantor = serializers.CharField(required=False)
    interest_rate_percentage = serializers.FloatField(required=False)
    is_overdue = serializers.BooleanField(required=False)
    last_payment_amount = serializers.FloatField(required=False)
    last_payment_date = serializers.DateField(required=False)
    last_statement_balance = serializers.FloatField(required=False)
    last_statement_issue_date = serializers.DateField(required=False)
    loan_name = serializers.CharField(required=False)
    loan_status = serializers.DictField(required=False)
    minimum_payment_amount = serializers.FloatField(required=False)
    next_payment_due_date = serializers.DateField(required=False)
    origination_date = serializers.DateField(required=False)
    origination_principal_amount = serializers.FloatField(required=False)
    outstanding_interest_amount = serializers.FloatField(required=False)
    payment_reference_number = serializers.CharField(required=False)
    pslf_status = serializers.DictField(required=False)
    repayment_plan = serializers.DictField(required=False)
    sequence_number = serializers.CharField(required=False)
    servicer_address = serializers.DictField(required=False)
    ytd_interest_paid = serializers.FloatField(required=False)
    ytd_principal_paid = serializers.FloatField(required=False)


class LiabilitiesSerializer(serializers.Serializer):
    student = StudentLoanSerializer(many=True)
    mortgage = MortgageSerializer(many=True)
