name: Rest API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: >
        docker-compose -f docker-compose.test.yml run --rm ledgetback sh -c "
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py test"
    - name: Lint
      run: docker-compose -f docker-compose.test.yml run --rm ledgetback sh -c "flake8 --config=./ledgetback/.flake8"
