name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployments_to_run:
        description: "Deployments to run"
        required: true
        type: choice
        options:
          - "all"
          - "force-run-all"
          - "webapps"
          - "webhome"
          - "webportal"
          - "landing"
          - "rest-api"
          - "lambda functions"
          - "oathkeeper"
          - "dynamic-router"
      force_run:
        description: "Force run all selected deployment's jobs"
        required: false
        type: boolean
        default: false
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        default: "uat"
        options:
          - "uat"
          - "prod"
permissions:
  id-token: write
  contents: read
jobs:
  deploy-rest-api:
    if: ${{ contains('all rest-api force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-rest-api.yml
    with:
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
      version: 1
      environment: ${{ inputs.environment }}
      role: 'arn:aws:iam::905418323334:role/gh-actions'
    secrets: inherit
  deploy-webhome-app:
    if: ${{ contains('all webhome force-run-all webapps', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: "webhome"
      version: 1
      s3-bucket: ${{ inputs.environment == 'uat' && 'uat.ledget.app' || 'ledget.app' }}
      role: 'arn:aws:iam::905418323334:role/gh-actions'
      environment: ${{ inputs.environment }}
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
  deploy-webportal-app:
    if: ${{ contains('all webportal force-run-all webapps', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: "webportal"
      version: 1
      s3-bucket: ${{ inputs.environment == 'uat' && 'uataccounts.ledget.app' || 'accounts.ledget.app' }}
      role: 'arn:aws:iam::905418323334:role/gh-actions'
      environment: ${{ inputs.environment }}
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
  deploy-landing-app:
    if: ${{ contains('all landing force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-landing-site.yml
    with:
      environment: ${{ inputs.environment }}
  deploy-oathkeeper:
    if: ${{ contains('all oathkeeper force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-oathkeeper.yml
    with:
      environment: ${{ inputs.environment }}
      role: 'arn:aws:iam::905418323334:role/gh-actions'
      version: 1
  deploy-dynamic-router:
    if: ${{ contains('all dynamic-router force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-dynamic-routing-lambda.yml
