name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployments_to_run:
        description: "Deployments to run"
        required: true
        type: choice
        options:
          - "all"
          - "force-run-all"
          - "webapps"
          - "web-app-main"
          - "web-app-portal"
          - "landing"
          - "rest-api"
          - "oathkeeper"
      force_run:
        description: "Force run all selected deployment's jobs"
        required: false
        type: boolean
        default: false
      version:
        description: "Version to deploy"
        required: true
        type: number
        default: 1
permissions:
  id-token: write
  contents: read
jobs:
  deploy-rest-api:
    if: ${{ contains('all rest-api force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-rest-api.yml
    with:
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
      version: ${{ inputs.version }}
      environment: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat' || 'prod' }}
      role: "arn:aws:iam::905418323334:role/gh-actions"
    secrets: inherit
  deploy-web-app-main:
    if: ${{ contains('all web-app-main force-run-all webapps', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: "web-app-main"
      version: ${{ inputs.version }}
      s3-bucket: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat.my.ledget.app' || 'my.ledget.app' }}
      role: "arn:aws:iam::905418323334:role/gh-actions"
      environment: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat' || 'prod' }}
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
  deploy-web-app-portal:
    if: ${{ contains('all web-app-portal force-run-all webapps', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: "web-app-portal"
      version: ${{ inputs.version }}
      s3-bucket: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat.accounts.ledget.app' || 'accounts.ledget.app' }}
      role: "arn:aws:iam::905418323334:role/gh-actions"
      environment: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat' || 'prod' }}
      force_run_all: ${{ inputs.deployments_to_run == 'force-run-all' || inputs.force_run == true }}
  deploy-landing-app:
    if: ${{ contains('all landing force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-landing-site.yml
    with:
      environment: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat' || 'prod' }}
  deploy-oathkeeper:
    if: ${{ contains('all oathkeeper force-run-all', inputs.deployments_to_run) }}
    uses: ./.github/workflows/deploy-oathkeeper.yml
    with:
      environment: ${{ (github.head_ref == 'uat' || github.ref_name == 'uat') && 'uat' || 'prod' }}
      role: "arn:aws:iam::905418323334:role/gh-actions"
      version: ${{ inputs.version }}
