on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      version:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      test-only:
        required: false
        type: boolean
      role:
        required: true
        type: string
jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
      - name: Use node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm ci
  build:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install
      - name: Build ${{ inputs.app }}
        run: nx run ${{ inputs.app }}:build
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Dummy Test
        run: echo "Dummy Test"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ !inputs.test-only }}
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: us-west-2
      - name: Copy app to s3
        run: |
          aws s3 sync ./front/apps/${{ inputs.app }}/dist
          s3://${{ inputs.s3-bucket }}.${{ inputs.version }}

