on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      version:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      test-only:
        required: false
        type: boolean
      role:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 8.11
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v3
        env:
          STORE_PATH: ${{ env.STORE_PATH }}
        with:
          path: ${{env.STORE_PATH}}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build ${{ inputs.app }}
        run: pnpm nx run ${{ inputs.app }}:build --mode ${{ inputs.environment }}
      - name: Dummy Test
        run: echo Dummy Test
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: us-west-2
      - name: Replace s3 bucket contents
        run: |
          aws s3 sync --delete ./apps/${{ inputs.app }}/dist s3://${{ inputs.s3-bucket }}.v${{ inputs.version }}
