name: Deploy Dynamic Routing Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
                - './lamba-dynamic-router/*'
  deploy:
    if: ${{ needs.changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch' }}
    needs: changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambad-dynamic-router
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::905418323334:role/gh-actions"
          aws-region: "us-west-2"
      - name: Zip Lambda
        shell: bash
        run: |
          zip -r lambda.zip .
      - name: Deploy Lambda
        run: |
          aws s3 sync --delete . s3://ledget-dynamic-route-lambda
