name: Rest Api Pipeline

on:
  workflow_call:
    inputs:
      force_run_all:
        description: "Run all jobs"
        required: false
        default: false
        type: "boolean"
      version:
        description: "Version of the API"
        required: true
        type: "string"
      environment:
        description: "Environment to deploy to"
        required: true
        type: "string"
      role:
        description: "Role to assume"
        required: true
        type: "string"
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
                - './back/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.src == true || inputs.force_run_all == true }}
    uses: ./.github/workflows/test-restapi.yml
    with:
      force_run_all: ${{ inputs.force_run_all }}
    secrets: inherit
  deploy:
    name: "Deploy Elastic Beanstalk Environment"
    defaults:
      run:
        working-directory: ./back/restapi
    needs: test
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        region: [us-west-2]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: "us-west-2"
      - name: Install EB CLI
        run: |
          sudo apt-get install python3-pip
          pip3 install awsebcli --upgrade
      - name: Initialize EB CLI
        env:
          REGION: ${{ matrix.region }}
        run: >
          eb init ledget-restapi \
            --modules restapi celery \
            --region $REGION \
            --platform "64bit Amazon Linux 2023 v4.3.2 running Python 3.11"
      - name: Update VERSION for restapi if needed
        working-directory: ./back/restapi
        run: VERSION=$(eb printenv | grep VERSION | cut -d'=' -f2);
          if [ "$VERSION" -ne "${{ inputs.version }}" ]; then eb setenv VERSION="${{ inputs.version }}"; fi
      - name: Update VERSION for celery if needed
        working-directory: ./back/celery
        run: VERSION=$(eb printenv | grep VERSION | cut -d'=' -f2);
            if [ "$VERSION" -ne "${{ inputs.version }}" ]; then eb setenv VERSION="${{ inputs.version }}"; fi
      - name: Deploy to Elastic Beanstalk
        working-directory: ./back
        run: eb deploy --modules restapi celery --env-group-suffix ${{ inputs.environment }}
