name: Deploy Landing Site

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
                - './front/apps/landing/**'
  build:
    if: ${{ needs.changes.outputs.src == 'true' || github.event_name == 'workflow_dispatch' }}
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1]
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::905418323334:role/gh-actions"
          aws-region: "us-west-2"
      - name: Install modules
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://landing.${{ matrix.version }}
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DIST_ID }} --paths "/*"
