name: Rest Api Pipeline

on:
    push:
      branches: [ "main", "uat", "dev" ]
    pull_request:
      branches: [ "main", "uat", "dev" ]
permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      output1: ${{ steps.filter.outputs.output1 }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          output1:
            - './back/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.output1 == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11]
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: >
        docker-compose -f docker-compose.test.yml run --rm ledgetback sh -c "
          python manage.py makemigrations &&
          python manage.py migrate &&
          python manage.py test"
    - name: Lint
      run: docker-compose -f docker-compose.test.yml run --rm ledgetback sh -c "flake8 --config=.flake8"
  build:
    # Don't build if pushing to dev branch
    if: ${{ github.ref != 'refs/heads/dev' }}
    name: "Build and Push to ECR"
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name: [ "ledget-rest-api", "oathkeeper" ]
        include:
          - image_name: "ledget-rest-api"
            context: "./back"
            version: v1
          - image_name: "oathkeeper"
            context: "./oathkeeper"
            version: v1
    # Build and push to correct ECR based on the branch
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build and push
        uses: ./.github/actions/build-and-push
        with:
          tag: ${{ matrix.image_name }}
          version: ${{ matrix.version }}
          context: ${{ matrix.context }}
          role: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::905418323334:role/ghactions-ecr' || github.ref == 'refs/heads/uat' && 'replace me' }}
          environment: ${{ github.base_ref || github.ref_name }}
