name: Test Rest API

on:
  push:
    branches: ["main", "uat", "dev"]
  workflow_call:
    inputs:
      force_run_all:
        required: false
        default: false
        type: "boolean"
  workflow_dispatch:
    inputs:
      force_run_all:
        required: false
        default: false
        type: "boolean"
jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
                - './back/**'
  test:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' || inputs.force_run_all == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: >
          docker-compose -f docker-compose.test.yml run --rm restapi sh -c "
            python manage.py migrate &&
            coverage run manage.py test"
      - name: Coverage
        run: docker-compose -f docker-compose.test.yml run --rm restapi sh -c "coverage report"
      - name: Lint
        run: docker-compose -f docker-compose.test.yml run --rm restapi sh -c "flake8 --config=.flake8"
