name: Build and Deploy Web Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
      - run: npm ci
  build:
      needs: install
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 16.x ]
      steps:
        - uses: actions/checkout@v3
        - name: Use node ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install
        - run: npm run build
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Test
        run: echo "Dummy Test"
  deploy:
