name: Web Apps Pipeline

on:
  push:
    branches: [ "main", "uat", "dev" ]
  pull_request:
    branches: [ "main", "uat", "dev" ]
  workflow_dispatch:
    inputs:
      apps_to_run:
        description: 'Select apps to run'
        required: false
        type: 'choice'
        default: 'all'
        options:
          - 'all'
          - 'webhome'
          - 'webportal'
      test_only:
        description: 'Run only tests'
        required: false
        type: 'boolean'
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
                - './back/**'
  depoly-webportal-app:
    if: ${{ needs.changes.outputs.src == true || (github.event_name == 'workflow_dispatch' && (github.event.inputs.apps_to_run == 'all' || github.event.inputs.apps_to_run == 'webportal'))}}
    needs: changes
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: 'webportal'
      version: 1
      s3-bucket: ${{ github.ref == 'refs/heads/uat' && 'uataccounts.ledget.app' || 'accounts.ledget.app' }}
      role: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::905418323334:role/gh-actions' || github.ref == 'refs/heads/uat' && 'replace me' }}
      test-only: ${{ github.ref == 'refs/heads/dev' || github.event.inputs.test_only == true }}
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.head_ref || github.ref_name }}
  deploy-webhome-app:
    if: ${{ needs.changes.outputs.src == true || (github.event_name == 'workflow_dispatch' && (github.event.inputs.apps_to_run == 'all' || github.event.inputs.apps_to_run == 'webhome'))}}
    needs: changes
    uses: ./.github/workflows/deploy-web-app.yml
    with:
      app: 'webhome'
      version: 1
      s3-bucket: ${{ github.ref == 'refs/heads/uat' && 'uat.ledget.app' || 'ledget.app' }}
      role: ${{ github.ref == 'refs/heads/main' && 'arn:aws:iam::905418323334:role/gh-actions' || github.ref == 'refs/heads/uat' && 'replace me' }}
      test-only: ${{ github.ref == 'refs/heads/dev' || github.event.inputs.test_only == true }}
      environment: ${{ github.ref == 'refs/heads/main' && 'prod' || github.head_ref || github.ref_name }}
